//! Generates the recipe registry from `src/recipes/*.rs` (github issue #295).
//!
//! Each recipe is one self-registering file: the FILE NAME (minus `.rs`) is the
//! catalog stem, and the file exports `pub fn recipe() -> Recipe`. This script
//! globs the directory and writes `$OUT_DIR/registry.rs` — the module
//! declarations plus the stem-sorted `all()` table — which `src/catalog.rs`
//! includes. Adding a recipe therefore touches only its new file plus the
//! shared regenerate-on-rebase census files (`tests/recipes-meta.json`, the
//! guix-dependence baseline — issue #296): no Rust source line is shared, the
//! mk/gates/ "one file per entry" property, so parallel recipe PRs don't
//! collide on a central table.
//!
//! Deterministic by construction: the registry is sorted by stem, never
//! `read_dir` order. Pure `std` — the crate stays dependency-free.

use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn Error>> {
    // A directory path makes cargo rescan the whole tree, so file adds/removes
    // and edits all retrigger the registry generation.
    println!("cargo:rerun-if-changed=src/recipes");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let recipes_dir = PathBuf::from(&manifest_dir).join("src/recipes");
    // (stem, module) pairs. The module name is the stem with '-' mapped to '_',
    // emitted as a raw identifier (`r#...`) so stems that collide with Rust
    // keywords (`true`, `move`, `loop`, ...) still compile.
    let mut recipes: Vec<(String, String)> = Vec::new();
    for entry in fs::read_dir(&recipes_dir)? {
        let entry = entry?;
        let name = entry.file_name();
        let name = name
            .to_str()
            .ok_or("non-UTF-8 filename in src/recipes")?;
        if entry.file_type()?.is_dir() {
            // A nested recipe would be silently absent from the catalog — and the
            // census manifest can't catch that (it is regenerated FROM the
            // catalog) — so directories are a hard error, never skipped.
            return Err(format!(
                "src/recipes/{name} is a directory — the recipe layout is FLAT, \
                 one <stem>.rs per recipe directly in src/recipes/"
            )
            .into());
        }
        if name.starts_with('.') {
            continue; // editor droppings (e.g. an emacs `.#foo.rs` lock link)
        }
        let Some(stem) = name.strip_suffix(".rs") else {
            continue;
        };
        // The stem is the catalog key and doubles as a module name, so keep it
        // to the charset every existing key uses and reject a digit lead.
        let ok = !stem.is_empty()
            && stem.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
            && !stem.starts_with(|c: char| c.is_ascii_digit());
        if !ok {
            return Err(format!(
                "src/recipes/{name}: stem must be [a-z0-9-]+, not digit-led \
                 (it becomes the catalog key and, with '-'->'_', a module name)"
            )
            .into());
        }
        let module = stem.replace('-', "_");
        if matches!(module.as_str(), "crate" | "self" | "super") {
            return Err(format!(
                "src/recipes/{name}: '{module}' cannot be a module name even as a \
                 raw identifier — rename the file"
            )
            .into());
        }
        recipes.push((stem.to_string(), module));
    }
    recipes.sort();
    if recipes.is_empty() {
        return Err("src/recipes is empty — the catalog would be vacuous".into());
    }

    let mut out = String::new();
    writeln!(out, "// @generated by build.rs from src/recipes/*.rs — do not edit.")?;
    for (stem, module) in &recipes {
        let path = format!("{manifest_dir}/src/recipes/{stem}.rs");
        writeln!(out, "#[path = {path:?}]")?;
        writeln!(out, "pub mod r#{module};")?;
    }
    writeln!(out, "pub fn all() -> Vec<(&'static str, crate::types::Recipe)> {{")?;
    writeln!(out, "    vec![")?;
    for (stem, module) in &recipes {
        writeln!(out, "        ({stem:?}, r#{module}::recipe()),")?;
    }
    writeln!(out, "    ]")?;
    writeln!(out, "}}")?;

    let out_path = PathBuf::from(env::var("OUT_DIR")?).join("registry.rs");
    fs::write(&out_path, out)?;
    Ok(())
}
