//! Generates the recipe registry from `src/recipes/*.rs` (github issue #295).
//!
//! Each recipe is one self-registering file: the FILE NAME (minus `.rs`) is the
//! catalog stem, and the file exports `pub fn recipe() -> Recipe`. This script
//! globs the directory and writes `$OUT_DIR/registry.rs` — the module
//! declarations plus the stem-sorted `all()` table — which `src/catalog.rs`
//! includes. Adding a recipe therefore touches ONLY its new file (the
//! mk/gates/ "one file per entry, no shared line" property, so parallel
//! recipe PRs never collide on a central table).
//!
//! Deterministic by construction: the registry is sorted by stem, never
//! `read_dir` order. Pure `std` — the crate stays dependency-free.

use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn Error>> {
    // A directory path makes cargo rescan the whole tree, so file adds/removes
    // and edits all retrigger the registry generation.
    println!("cargo:rerun-if-changed=src/recipes");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let recipes_dir = PathBuf::from(&manifest_dir).join("src/recipes");
    let mut stems: Vec<String> = Vec::new();
    for entry in fs::read_dir(&recipes_dir)? {
        let name = entry?.file_name();
        let name = name
            .to_str()
            .ok_or("non-UTF-8 filename in src/recipes")?;
        if let Some(stem) = name.strip_suffix(".rs") {
            // The stem doubles as a Rust module name (with `-` mapped to `_`),
            // so reject anything that would not survive that mapping.
            let ok = !stem.is_empty()
                && stem.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
                && !stem.starts_with(|c: char| c.is_ascii_digit());
            if !ok {
                return Err(format!(
                    "src/recipes/{name}: stem must be [a-z0-9-]+, not digit-led \
                     (it becomes the catalog key and, with '-'->'_', a module name)"
                )
                .into());
            }
            stems.push(stem.to_string());
        }
    }
    stems.sort();
    if stems.is_empty() {
        return Err("src/recipes is empty — the catalog would be vacuous".into());
    }

    let mut out = String::new();
    writeln!(out, "// @generated by build.rs from src/recipes/*.rs — do not edit.")?;
    for stem in &stems {
        let module = stem.replace('-', "_");
        writeln!(out, "#[path = \"{}/src/recipes/{stem}.rs\"]", manifest_dir.escape_debug())?;
        writeln!(out, "pub mod {module};")?;
    }
    writeln!(out, "pub fn all() -> Vec<(&'static str, crate::types::Recipe)> {{")?;
    writeln!(out, "    vec![")?;
    for stem in &stems {
        let module = stem.replace('-', "_");
        writeln!(out, "        ({stem:?}, {module}::recipe()),")?;
    }
    writeln!(out, "    ]")?;
    writeln!(out, "}}")?;

    let out_path = PathBuf::from(env::var("OUT_DIR")?).join("registry.rs");
    fs::write(&out_path, out)?;
    Ok(())
}
