"""Optional public-fixture generator; no build/test/runtime dependency.

Usage: python3 p256_vectors.py ECCCDH.zip ECDSA.zip /path/to/libcrypto.so
The two NIST CAVP archives are pinned below. OpenSSL 3.5.7 supplies the
additional point and rare-signature oracles; Python integers supply field
oracles. No td implementation is imported and no network access is used.
"""

import ctypes as c
import hashlib
import io
import sys
import zipfile
from pathlib import Path

P = 2**256 - 2**224 + 2**192 + 2**96 - 1
N = int("ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551", 16)


def archive(path, digest):
    data = Path(path).read_bytes()
    if hashlib.sha256(data).hexdigest() != digest:
        raise ValueError("NIST archive digest mismatch")
    return zipfile.ZipFile(io.BytesIO(data))


def records(archive, entry, section):
    text = archive.read(entry).decode().replace("\r", "")
    part = text.split(section, 1)[1].split("[", 1)[0]
    return [dict(line.split(" = ", 1) for line in block.splitlines())
            for block in part.strip().split("\n\n") if block.strip()]


ecdh = archive(sys.argv[1], "5fff092551f2d72e89a3d9362711878708f9a14b502f0dfae819649105b0ea39")
ecdsa = archive(sys.argv[2], "fe47cc92b4cee418236125c9ffbcd9bb01c8c34e74a4ba195d954bcb72824752")
print("# Public P-256 fixtures; generated by p256_vectors.py")
print("# NIST ECCCDH P-256: ecdh d Qx Qy peer_x peer_y Z")
rows = records(ecdh, "KAS_ECC_CDH_PrimitiveTest.txt", "[P-256]")
if len(rows) != 25:
    raise ValueError("unexpected ECCCDH corpus")
for row in rows:
    print("ecdh", *(row[key] for key in ["dIUT", "QIUTx", "QIUTy", "QCAVSx", "QCAVSy", "ZIUT"]))
print("# NIST ECDSA P-256/SHA-256: verify P/F digest Qx Qy r s")
rows = records(ecdsa, "186-4ecdsatestvectors/SigVer.rsp", "[P-256,SHA-256]")
if len(rows) != 15:
    raise ValueError("unexpected SigVer corpus")
for row in rows:
    digest = hashlib.sha256(bytes.fromhex(row["Msg"])).hexdigest()
    print("verify", row["Result"][0], digest, *(row[key] for key in ["Qx", "Qy", "R", "S"]))
print("# NIST public-key validation: public P/F x y (overwide values retained)")
rows = records(ecdsa, "186-4ecdsatestvectors/PKV.rsp", "[P-256]")
if len(rows) != 12:
    raise ValueError("unexpected PKV corpus")
for row in rows:
    print("public", row["Result"][0], row["Qx"], row["Qy"])

print("# Python integer arithmetic: field p/n a b sum difference product inverse_a")
for name, modulus in [("p", P), ("n", N)]:
    edges = [0, 1, 2, modulus - 2, modulus - 1]
    edges += [2**bit + offset for bit in [64, 128, 192, 255] for offset in [-1, 0]]
    pairs = [(value, modulus - 1) for value in edges]
    pairs += [(value, value) for value in edges]
    for index in range(8):
        seed = b"td-secret/p256/field/v1/" + name.encode() + bytes([index])
        a = int.from_bytes(hashlib.sha256(seed + b"a").digest()) % modulus
        b = int.from_bytes(hashlib.sha256(seed + b"b").digest()) % modulus
        pairs.append((a, b))
    for a, b in pairs:
        values = [a, b, (a+b) % modulus, (a-b) % modulus,
                  a*b % modulus, pow(a, modulus-2, modulus)]
        print("field", name, *(f"{x:064x}" for x in values))

lib = c.CDLL(sys.argv[3])
ptr = c.c_void_p
integer = c.c_int


def bind(name, result, arguments):
    fn = getattr(lib, name)
    fn.restype = result
    fn.argtypes = arguments
    return fn


def require(value):
    if not value:
        raise RuntimeError("OpenSSL fixture operation failed")
    return value


bn_new = bind("BN_new", ptr, [])
bn_from = bind("BN_bin2bn", ptr, [ptr, integer, ptr])
bn_bytes = bind("BN_bn2binpad", integer, [ptr, ptr, integer])
bn_free = bind("BN_free", None, [ptr])
ctx_new = bind("BN_CTX_new", ptr, [])
ctx_free = bind("BN_CTX_free", None, [ptr])
nid = bind("OBJ_txt2nid", integer, [c.c_char_p])
group_new = bind("EC_GROUP_new_by_curve_name", ptr, [integer])
group_free = bind("EC_GROUP_free", None, [ptr])
point_new = bind("EC_POINT_new", ptr, [ptr])
point_free = bind("EC_POINT_free", None, [ptr])
mul = bind("EC_POINT_mul", integer, [ptr, ptr, ptr, ptr, ptr, ptr])
coordinates = bind("EC_POINT_get_affine_coordinates", integer, [ptr, ptr, ptr, ptr, ptr])
compressed = bind("EC_POINT_set_compressed_coordinates", integer, [ptr, ptr, ptr, integer, ptr])
key_new = bind("EC_KEY_new_by_curve_name", ptr, [integer])
key_set = bind("EC_KEY_set_public_key", integer, [ptr, ptr])
key_free = bind("EC_KEY_free", None, [ptr])
sig_new = bind("ECDSA_SIG_new", ptr, [])
sig_set = bind("ECDSA_SIG_set0", integer, [ptr, ptr, ptr])
sig_free = bind("ECDSA_SIG_free", None, [ptr])
verify = bind("ECDSA_do_verify", integer, [ptr, integer, ptr, ptr])
curve = require(nid(b"prime256v1"))
group = require(group_new(curve))
ctx = require(ctx_new())


def bn(value):
    return require(bn_from(value.to_bytes(32), 32, None))


def xy(point):
    x, y = require(bn_new()), require(bn_new())
    try:
        require(coordinates(group, point, x, y, ctx) == 1)
        out = []
        for word in [x, y]:
            data = c.create_string_buffer(32)
            require(bn_bytes(word, data, 32) == 32)
            out.append(data.raw.hex())
        return out
    finally:
        bn_free(x)
        bn_free(y)


def multiple(value, point=None):
    scalar, out = bn(value), require(point_new(group))
    try:
        require(mul(group, out, None if point else scalar,
                    point, scalar if point else None, ctx) == 1)
        return out
    except BaseException:
        point_free(out)
        raise
    finally:
        bn_free(scalar)


try:
    print("# OpenSSL 3.5.7 boundary/pattern scalar point and ECDH oracles")
    values = [1, 2, 3, N-1, N-2, 2**63, 2**64, 2**127, 2**128,
              2**191, 2**192, 2**255, int("aa"*32, 16), int("55"*32, 16)]
    values += [int.from_bytes(hashlib.sha256(bytes([i])).digest()) % (N-1) + 1 for i in [0, 1]]
    for index, value in enumerate(values):
        peer_d = int.from_bytes(hashlib.sha256(b"td-secret/p256/peer/v1/" + bytes([index])).digest()) % (N-1) + 1
        own, peer = multiple(value), multiple(peer_d)
        shared = multiple(value, peer)
        try:
            print("edge", f"{value:064x}", *xy(own), *xy(peer), xy(shared)[0])
        finally:
            for point in [own, peer, shared]:
                point_free(point)

    print("# OpenSSL ECDH fixture with a leading-zero shared x, private scalar 2")
    own = multiple(2)
    try:
        for peer_d in range(1, 4097):
            peer = multiple(peer_d)
            shared = multiple(2, peer)
            try:
                shared_x = xy(shared)[0]
                if shared_x.startswith("00"):
                    print("leading", f"{2:064x}", *xy(own), *xy(peer), shared_x)
                    break
            finally:
                point_free(shared)
                point_free(peer)
        else:
            raise RuntimeError("no leading-zero ECDH fixture")
    finally:
        point_free(own)

    print("# OpenSSL-verified valid ES256 case whose verification point has x >= n")
    point = require(point_new(group))
    try:
        for r in range(1, 64):
            x = bn(N+r)
            try:
                if compressed(group, point, x, 0, ctx) == 1:
                    break
            finally:
                bn_free(x)
        else:
            raise RuntimeError("no rare-x fixture")
        public = multiple(pow(r, -1, N), point)
        key, signature = require(key_new(curve)), require(sig_new())
        try:
            require(key_set(key, public) == 1)
            require(sig_set(signature, bn(r), bn(1)) == 1)
            require(verify(bytes(32), 32, signature, key) == 1)
            print("rare", "P", "00"*32, *xy(public), f"{r:064x}", f"{1:064x}")
        finally:
            sig_free(signature)
            key_free(key)
            point_free(public)
    finally:
        point_free(point)

    print("# OpenSSL-verified prehashed ES256 at digest n, n+1, and 2^256-1")
    generator = multiple(1)
    try:
        r = int(xy(generator)[0], 16) % N
    finally:
        point_free(generator)
    for digest in [N, N+1, 2**256-1]:
        # k=1, s=2: Q=((2-digest)/r)*G, independently checked by OpenSSL.
        public = multiple((2-digest)*pow(r, -1, N) % N)
        key, signature = require(key_new(curve)), require(sig_new())
        try:
            require(key_set(key, public) == 1)
            require(sig_set(signature, bn(r), bn(2)) == 1)
            require(verify(digest.to_bytes(32), 32, signature, key) == 1)
            print("hash", "P", f"{digest:064x}", *xy(public), f"{r:064x}", f"{2:064x}")
        finally:
            sig_free(signature)
            key_free(key)
            point_free(public)
finally:
    ctx_free(ctx)
    group_free(group)
