format=1
color-scheme=1
accent-color=0.125,0.375,0.75
contrast=0
gtk-theme=Adwaita
icon-theme=Adwaita
cursor-theme=Adwaita
cursor-size=24
font-name=Sans 11
document-font-name=Sans 11
monospace-font-name=Monospace 11
