//! The account database: `/etc/passwd`, `/etc/group`, `/etc/shadow`.
//!
//! Parsing is fail-closed (THREAT-MODEL.md §7). A malformed line fails the whole
//! lookup instead of being skipped — skipping is how a crafted entry shadows a
//! real one — and a duplicate user name is an error rather than a first-wins or
//! last-wins guess. On a td image these files are immutable EROFS content
//! generated by `system-x86-64`, so the adversary here is a tailoring mistake;
//! the parser does not treat that as a reason to trust them.

use std::fs;

pub const PASSWD: &str = "/etc/passwd";
pub const GROUP: &str = "/etc/group";
pub const SHADOW: &str = "/etc/shadow";

/// One `/etc/passwd` entry. `gecos` is carried because `login` has no use for it
/// and dropping it would make the seven-field check look like six.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Account {
    pub name: String,
    pub uid: u32,
    pub gid: u32,
    pub gecos: String,
    pub home: String,
    pub shell: String,
}

/// What `/etc/shadow`'s password field says about an account. The classification
/// IS the authentication policy; see `may_start_session`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Secret {
    /// Empty field: no password is required.
    NoPassword,
    /// `!`, `!!`, `*`, or any `!`-prefixed hash — administratively locked.
    Locked,
    /// Exact td image marker: locked for every human session and available
    /// only to the service-specific credential path.
    Service,
    /// A hash this build cannot verify. Denied, never treated as absent.
    Hashed,
}

/// Why a session was refused, so the caller can say so precisely. A single
/// "denied" would make an operator debug the wrong thing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Denied {
    /// The account is locked; even `login -f` will not revive it.
    Locked,
    /// The account has a password and this build verifies no hash scheme.
    NeedsPassword,
    /// The account is a service identity, not a human session.
    ServiceOnly,
    /// The service path was pointed at an interactive or ordinarily locked
    /// account rather than an explicitly marked service identity.
    NotService,
}

/// The whole authentication decision, in one place.
///
/// `forced` is `login -f` / a root-invoked `su`: the CALLER has already
/// established the right to start this session, so no secret is consulted —
/// except that a locked account stays locked (THREAT-MODEL.md §3).
pub fn may_start_session(secret: Secret, forced: bool) -> Result<(), Denied> {
    match secret {
        Secret::Locked => Err(Denied::Locked),
        Secret::Service => Err(Denied::ServiceOnly),
        Secret::NoPassword => Ok(()),
        Secret::Hashed if forced => Ok(()),
        Secret::Hashed => Err(Denied::NeedsPassword),
    }
}

/// Admit only the exact service-account class.
///
/// This is intentionally not a `forced` branch above. `login -f`, `su`, and
/// ordinary `exec-as` must keep refusing a service account, while a unit must
/// not use the service path to enter an interactive account.
pub fn may_start_service(secret: Secret) -> Result<(), Denied> {
    match secret {
        Secret::Service => Ok(()),
        Secret::Locked | Secret::NoPassword | Secret::Hashed => Err(Denied::NotService),
    }
}

pub fn classify(field: &str) -> Secret {
    if field.is_empty() {
        return Secret::NoPassword;
    }
    if field == "!td-service" {
        return Secret::Service;
    }
    // `*` and anything `!`-prefixed are the two spellings shadow-utils, busybox
    // and util-linux all agree mean "cannot authenticate". `!` in front of an
    // otherwise valid hash is how `passwd -l` locks an account without losing it.
    if field == "*" || field.starts_with('!') {
        return Secret::Locked;
    }
    Secret::Hashed
}

/// Read a database file. A missing file is an error, not an empty database:
/// "no /etc/shadow" must not read as "no account has a password".
fn read(path: &str) -> Result<String, String> {
    fs::read_to_string(path).map_err(|e| format!("cannot read {path}: {e}"))
}

/// Split one colon-separated line into exactly `want` fields, or fail. Trailing
/// empty fields are real fields (`root:x:0:0::/root:/bin/sh` has two), so this
/// counts separators rather than trimming.
fn fields<'a>(line: &'a str, want: usize, path: &str, lineno: usize) -> Result<Vec<&'a str>, String> {
    let got: Vec<&str> = line.split(':').collect();
    if got.len() != want {
        return Err(format!(
            "{path}:{lineno}: expected {want} colon-separated fields, got {}",
            got.len()
        ));
    }
    Ok(got)
}

/// Every non-empty line of a database file, numbered from 1. Blank lines are the
/// only thing skipped — a trailing newline yields one, and it carries no entry.
fn entries(text: &str) -> impl Iterator<Item = (usize, &str)> {
    text.lines()
        .enumerate()
        .map(|(i, line)| (i + 1, line))
        .filter(|(_, line)| !line.trim().is_empty())
}

fn number(path: &str, lineno: usize, what: &str, token: &str) -> Result<u32, String> {
    token
        .parse::<u32>()
        .map_err(|_| format!("{path}:{lineno}: {what} {token:?} is not an unsigned 32-bit id"))
}

/// Look one account up. Every line is parsed even after a hit: a malformed or
/// duplicate entry LATER in the file is exactly the tampering this refuses to
/// resolve, and stopping early would never see it.
pub fn account_in(text: &str, path: &str, want: &str) -> Result<Account, String> {
    let mut hit: Option<Account> = None;
    for (lineno, line) in entries(text) {
        let f = fields(line, 7, path, lineno)?;
        let (Some(name), Some(uid), Some(gid), Some(gecos), Some(home), Some(shell)) =
            (f.first(), f.get(2), f.get(3), f.get(4), f.get(5), f.get(6))
        else {
            return Err(format!("{path}:{lineno}: malformed entry"));
        };
        if *name != want {
            continue;
        }
        if hit.is_some() {
            return Err(format!(
                "{path}:{lineno}: user {want:?} appears more than once; refusing to \
                 choose between conflicting entries"
            ));
        }
        let uid = number(path, lineno, "uid", uid)?;
        let gid = number(path, lineno, "gid", gid)?;
        // `login` execs the shell by absolute path with no PATH search, and
        // chdir's to the home; a relative one would resolve against whatever
        // directory the caller happened to be in.
        for (what, value) in [("home", *home), ("shell", *shell)] {
            if !value.starts_with('/') {
                return Err(format!(
                    "{path}:{lineno}: {what} {value:?} is not an absolute path"
                ));
            }
        }
        hit = Some(Account {
            name: (*name).to_string(),
            uid,
            gid,
            gecos: (*gecos).to_string(),
            home: (*home).to_string(),
            shell: (*shell).to_string(),
        });
    }
    hit.ok_or_else(|| format!("{path}: no such user {want:?}"))
}

pub fn account(name: &str) -> Result<Account, String> {
    account_in(&read(PASSWD)?, PASSWD, name)
}

/// The gids of every group that lists `user` as a member. The primary gid is NOT
/// added here — `Credentials::new` does that, so there is one place that decides
/// what the complete set is.
pub fn supplementary_in(text: &str, path: &str, user: &str) -> Result<Vec<u32>, String> {
    let mut gids = Vec::new();
    for (lineno, line) in entries(text) {
        let f = fields(line, 4, path, lineno)?;
        let (Some(gid), Some(members)) = (f.get(2), f.get(3)) else {
            return Err(format!("{path}:{lineno}: malformed entry"));
        };
        // Parsed for EVERY line, member or not: a group file with an unparseable
        // gid is a broken file, and answering from the lines that happened to
        // parse would hand out a set that is quietly too small.
        let gid = number(path, lineno, "gid", gid)?;
        // EXACT, not trimmed: trimming is the permissive direction — it would grant
        // a group on a whitespace-padded member field — and every other name match
        // in this file is exact. The empty check keeps an empty member slot in
        // `a,,b` from matching an empty user name.
        let member = members.split(',').any(|m| !m.is_empty() && m == user);
        if member {
            gids.push(gid);
        }
    }
    gids.sort_unstable();
    gids.dedup();
    Ok(gids)
}

pub fn supplementary(user: &str) -> Result<Vec<u32>, String> {
    supplementary_in(&read(GROUP)?, GROUP, user)
}

/// `shadow(5)`: name, password, last change, min, max, warn, inactive, expire,
/// reserved. `build_shadow` writes all nine.
const SHADOW_FIELDS: usize = 9;

/// The shadow entry for one account. A missing entry is an error, so an account
/// present in `/etc/passwd` but absent from `/etc/shadow` cannot log in.
pub fn secret_in(text: &str, path: &str, user: &str) -> Result<Secret, String> {
    let mut hit: Option<Secret> = None;
    for (lineno, line) in entries(text) {
        // The whole record, not just the two fields that carry the decision.
        // Accepting a SHORT line is how corruption becomes authentication: a
        // truncated `root:` has an empty password field, and an empty password
        // field means NoPassword — so losing the tail of a LOCKED account's
        // entry would turn it into one anybody may log into. td writes exactly
        // nine fields (shadow(5)); anything else is not this file.
        let f = fields(line, SHADOW_FIELDS, path, lineno)?;
        let (Some(name), Some(field)) = (f.first(), f.get(1)) else {
            return Err(format!("{path}:{lineno}: expected at least name:password"));
        };
        if *name != user {
            continue;
        }
        if hit.is_some() {
            return Err(format!(
                "{path}:{lineno}: user {user:?} appears more than once; refusing to \
                 choose between conflicting entries"
            ));
        }
        hit = Some(classify(field));
    }
    hit.ok_or_else(|| format!("{path}: no entry for user {user:?}"))
}

pub fn secret(user: &str) -> Result<Secret, String> {
    secret_in(&read(SHADOW)?, SHADOW, user)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::indexing_slicing)]
    use super::*;

    /// What `system-x86-64` generates today, verbatim in shape.
    const PW: &str = "root:x:0:0:root:/root:/bin/sh\n\
                      tester:x:1000:1000:Test User:/home/tester:/bin/sh\n";
    const GR: &str = "root:x:0:\ntester:x:1000:\nwheel:x:10:tester\ntty:x:5:\n";
    const SH: &str = "root::19000:0:99999:7:::\ntester::19000:0:99999:7:::\n";

    #[test]
    fn the_shipped_database_resolves() {
        let tester = account_in(PW, PASSWD, "tester").unwrap();
        assert_eq!(tester.uid, 1000);
        assert_eq!(tester.gid, 1000);
        assert_eq!(tester.home, "/home/tester");
        assert_eq!(tester.shell, "/bin/sh");
        assert_eq!(account_in(PW, PASSWD, "root").unwrap().uid, 0);
        assert_eq!(supplementary_in(GR, GROUP, "tester").unwrap(), vec![10]);
        assert_eq!(supplementary_in(GR, GROUP, "root").unwrap(), Vec::<u32>::new());
        assert_eq!(secret_in(SH, SHADOW, "tester").unwrap(), Secret::NoPassword);
    }

    /// A TRUNCATED shadow record must not read as "no password". This is the
    /// direction corruption runs in: the password field is the SECOND of nine,
    /// so a line that loses its tail keeps a name and an empty secret — and an
    /// empty secret is the one class interactive `login` lets through. A locked
    /// account whose entry got shortened would become one anybody may log into.
    #[test]
    fn a_truncated_shadow_record_is_refused_rather_than_read_as_passwordless() {
        for truncated in [
            "tester:",
            "tester::",
            "tester::19000",
            "tester::19000:0:99999:7::",
            "tester:!:19000:0:99999:7::::extra",
        ] {
            let text = format!("root::19000:0:99999:7:::\n{truncated}\n");
            let err = secret_in(&text, SHADOW, "tester").unwrap_err();
            assert!(
                err.contains("colon-separated fields"),
                "{truncated:?} must be refused as malformed, got: {err}"
            );
        }
        // The refusal is for the whole LOOKUP, not just the bad line: a
        // malformed entry anywhere means this is not a file to authenticate
        // against, whoever is being looked up.
        let text = format!("{SH}broken:\n");
        assert!(secret_in(&text, SHADOW, "root").is_err());
    }

    #[test]
    fn an_unknown_user_is_an_error_not_an_empty_account() {
        assert!(account_in(PW, PASSWD, "nobody").is_err());
        assert!(secret_in(SH, SHADOW, "nobody").is_err());
        // ...but an unknown user simply belongs to no groups.
        assert_eq!(supplementary_in(GR, GROUP, "nobody").unwrap(), Vec::<u32>::new());
    }

    /// The duplicate-entry refusal, both files. "First wins" and "last wins" are
    /// each a defensible convention and each one an attacker's choice of which
    /// entry to append.
    #[test]
    fn a_duplicate_user_is_refused_rather_than_resolved() {
        let doubled = format!("{PW}tester:x:0:0::/root:/bin/sh\n");
        let err = account_in(&doubled, PASSWD, "tester").unwrap_err();
        assert!(err.contains("more than once"), "{err}");
        let doubled = format!("{SH}tester::19000:0:99999:7:::\n");
        assert!(secret_in(&doubled, SHADOW, "tester").is_err());
        // A duplicate of a DIFFERENT user is still not this user's problem.
        let other = format!("{PW}root:x:0:0::/root:/bin/sh\n");
        assert!(account_in(&other, PASSWD, "tester").is_ok());
        assert!(account_in(&other, PASSWD, "root").is_err());
    }

    /// A malformed line fails the lookup even when the wanted entry parsed
    /// cleanly, and even when it sits AFTER the hit. Skipping it is how a
    /// truncated line hides a second entry on the same physical line.
    #[test]
    fn a_malformed_line_fails_the_whole_lookup() {
        let short = format!("{PW}broken:x:2\n");
        let err = account_in(&short, PASSWD, "tester").unwrap_err();
        assert!(err.contains("expected 7"), "{err}");
        assert!(account_in("root:x:0:0:r:/root:/bin/sh:extra\n", PASSWD, "root").is_err());
        assert!(supplementary_in("wheel:x:10\n", GROUP, "tester").is_err());
        assert!(supplementary_in("wheel:x:ten:tester\n", GROUP, "tester").is_err());
        assert!(account_in("root:x:zero:0:r:/root:/bin/sh\n", PASSWD, "root").is_err());
        // Blank lines are the one thing skipped: a trailing newline makes one.
        assert!(account_in(&format!("\n{PW}\n"), PASSWD, "root").is_ok());
    }

    #[test]
    fn a_relative_home_or_shell_is_refused() {
        assert!(account_in("u:x:1:1:u:home:/bin/sh\n", PASSWD, "u").is_err());
        assert!(account_in("u:x:1:1:u:/home/u:sh\n", PASSWD, "u").is_err());
        assert!(account_in("u:x:1:1:u:/home/u:/bin/sh\n", PASSWD, "u").is_ok());
    }

    /// Group membership is exact, not substring. `test` must not inherit
    /// `tester`'s groups, and an empty member slot must not match an empty name.
    #[test]
    fn group_membership_matches_whole_names_only() {
        let g = "wheel:x:10:tester,root\nops:x:20:test\nempty:x:30:,\n";
        assert_eq!(supplementary_in(g, GROUP, "tester").unwrap(), vec![10]);
        assert_eq!(supplementary_in(g, GROUP, "test").unwrap(), vec![20]);
        assert_eq!(supplementary_in(g, GROUP, "root").unwrap(), vec![10]);
        assert_eq!(supplementary_in(g, GROUP, "").unwrap(), Vec::<u32>::new());
    }

    #[test]
    fn the_password_field_classifies_the_way_the_policy_table_says() {
        assert_eq!(classify(""), Secret::NoPassword);
        assert_eq!(classify("*"), Secret::Locked);
        assert_eq!(classify("!"), Secret::Locked);
        assert_eq!(classify("!!"), Secret::Locked);
        assert_eq!(classify("!$6$salt$hash"), Secret::Locked);
        assert_eq!(classify("!td-service"), Secret::Service);
        assert_eq!(classify("$6$salt$hash"), Secret::Hashed);
        assert_eq!(classify("x"), Secret::Hashed);
    }

    /// The policy table of THREAT-MODEL.md §3, asserted as a table. The row that
    /// matters most is `Locked` under `forced`: busybox's `login -f` skips the
    /// database entirely, so a locked account could be revived by editing
    /// /etc/autologin. Here it cannot.
    #[test]
    fn the_authentication_policy_denies_everything_it_cannot_verify() {
        assert_eq!(may_start_session(Secret::NoPassword, false), Ok(()));
        assert_eq!(may_start_session(Secret::NoPassword, true), Ok(()));
        assert_eq!(
            may_start_session(Secret::Hashed, false),
            Err(Denied::NeedsPassword)
        );
        assert_eq!(may_start_session(Secret::Hashed, true), Ok(()));
        assert_eq!(may_start_session(Secret::Locked, false), Err(Denied::Locked));
        assert_eq!(may_start_session(Secret::Locked, true), Err(Denied::Locked));
        assert_eq!(
            may_start_session(Secret::Service, false),
            Err(Denied::ServiceOnly)
        );
        assert_eq!(
            may_start_session(Secret::Service, true),
            Err(Denied::ServiceOnly)
        );
        assert_eq!(may_start_service(Secret::Service), Ok(()));
        for secret in [Secret::NoPassword, Secret::Locked, Secret::Hashed] {
            assert_eq!(may_start_service(secret), Err(Denied::NotService));
        }
    }
}
