# tests/td-system-lib.sh — the shared td-system input-resolution seam for the
# gates that pack/load the SHIPPED td system image (120-oci, 135-oci-load), so
# the resolution logic and the honest stale-lock diagnostics live in ONE place.
# Sourced after tests/cache-lib.sh (load_stage0 provides the td-builder).
#
# td_system_closure TB OUTFILE — resolve the SHIPPED td system's runtime closure
# with NO guix process, from the PINNED lowering lock tests/td-system.lock
# (regenerated by tools/td-system-lock-regen.sh on a channel bump or td-system
# re-baseline). Four checks, each its own FAIL:
#   1. INPUT PINS — re-hash the LIVE lowering inputs (channels.scm + the system
#      declaration modules) against the lock's input-sha256-* entries: a channel
#      bump or an oracle re-baseline reds HERE, deterministically — staleness is
#      input-anchored, not a heuristic, so a stale pinned root cannot pass.
#   2. ROOT — the pinned system out path must exist in the store (the capture
#      realizes it; a cold/GC'd store reds honestly, distinctly from staleness).
#   3. CLOSURE — `td-builder store-closure-scan` content-scans the runtime
#      closure from the root into OUTFILE (no guix repl, no /var/guix/db read).
#   4. CLOSURE PIN — OUTFILE's sha256 must equal the lock's closure-sha256 (the
#      capture ran the SAME scan): a truncated scan (partially GC'd/imported
#      store) or a grown one (new on-disk byte-ref candidates) reds instead of
#      shipping different image bytes per host.
td_system_closure() {
  _tsc_tb="$1"; _tsc_out="$2"
  _tsc_lock="tests/td-system.lock"
  _tsc_regen="regenerate the lock HOST-SIDE: sh tools/td-system-lock-regen.sh (channel bump / td-system re-baseline; an exclusive landing)"
  # The input list comes from the LOCK's own input-sha256-* keys (one source of
  # truth — the capture tool's lowering-inputs list), so an input pinned by a
  # future capture can never be silently unchecked here. Two anchors that can
  # never legitimately disappear are required, so a truncated lock reds too.
  _tsc_inputs=`sed -n 's/^input-sha256-\([^ ]*\) .*/\1/p' "$_tsc_lock"` \
    || { echo "FAIL: cannot read $_tsc_lock — $_tsc_regen" >&2; return 1; }
  for _tsc_anchor in channels.scm system/td.scm; do
    printf '%s\n' "$_tsc_inputs" | grep -qxF "$_tsc_anchor" \
      || { echo "FAIL: $_tsc_lock has no input-sha256-$_tsc_anchor pin — the lock is truncated or pre-dates input anchoring; $_tsc_regen" >&2; return 1; }
  done
  for _tsc_f in $_tsc_inputs; do
    _tsc_want=`"$_tsc_tb" resolve "$_tsc_lock" "input-sha256-$_tsc_f"` \
      || { echo "FAIL: $_tsc_lock has no input-sha256-$_tsc_f entry — $_tsc_regen" >&2; return 1; }
    _tsc_got=`sha256sum "$_tsc_f" | cut -d' ' -f1`
    test "$_tsc_want" = "$_tsc_got" \
      || { echo "FAIL: $_tsc_lock is STALE — $_tsc_f changed since capture (live sha256 $_tsc_got != pinned $_tsc_want), so the pinned system root no longer reflects the declared system; $_tsc_regen" >&2; return 1; }
  done
  _tsc_root=`"$_tsc_tb" resolve "$_tsc_lock" td-system` \
    || { echo "FAIL: could not resolve td-system from $_tsc_lock" >&2; return 1; }
  test -d "$_tsc_root" \
    || { echo "FAIL: the pinned td system root $_tsc_root is not in the store — the lock itself is CURRENT (input pins match); the store is cold or GC'd, re-warm it: $_tsc_regen" >&2; return 1; }
  "$_tsc_tb" store-closure-scan /gnu/store "$_tsc_root" > "$_tsc_out" \
    || { echo "FAIL: td-builder store-closure-scan failed on $_tsc_root" >&2; return 1; }
  test -s "$_tsc_out" || { echo "FAIL: empty td system closure (scan of $_tsc_root)" >&2; return 1; }
  _tsc_wanthash=`"$_tsc_tb" resolve "$_tsc_lock" closure-sha256` \
    || { echo "FAIL: $_tsc_lock has no closure-sha256 entry — $_tsc_regen" >&2; return 1; }
  _tsc_gothash=`sha256sum < "$_tsc_out" | cut -d' ' -f1`
  test "$_tsc_wanthash" = "$_tsc_gothash" \
    || { echo "FAIL: the scanned td system closure (`grep -c . "$_tsc_out"` paths, sha256 $_tsc_gothash) != the pinned capture (closure-sha256 $_tsc_wanthash) — the store is missing closure members (partial GC/import) or new byte-ref candidates appeared on disk; $_tsc_regen" >&2; return 1; }
}
