//! Fixed-output source pins owned by the recipe catalog.
//!
//! This replaces the old external source lock directory. The keys are the
//! staged input names recipes declare through `source_input(...)` or `inputs`.

use crate::types::SourcePin;

struct PinDef {
    key: &'static str,
    aliases: &'static [&'static str],
    url: &'static str,
    sha256: &'static str,
    file: &'static str,
}

const PINS: &[PinDef] = &[
    PinDef {
        key: "bash-mesboot-source",
        aliases: &[],
        // GNU bash 2.05b — the from-source bootstrap shell (re #469). Same
        // version live-bootstrap builds under tcc + mes libc (its parser
        // regenerated by the oyacc rung's `yacc`) to replace the host bash.
        url: "https://ftp.gnu.org/gnu/bash/bash-2.05b.tar.gz",
        sha256: "ba03d412998cc54bd0b0f2d6c32100967d3137098affdc2d32e6e7c11b163fe4",
        file: "bash-2.05b.tar.gz",
    },
    PinDef {
        key: "binutils-mesboot-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/binutils/binutils-2.20.1a.tar.bz2",
        sha256: "71d37c96451333c5c0b84b170169fdcb138bbb27397dc06281905d9717c8ed64",
        file: "binutils-2.20.1a.tar.bz2",
    },
    PinDef {
        key: "binutils-244-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/binutils/binutils-2.44.tar.xz",
        sha256: "ce2017e059d63e67ddb9240e9d4ec49c2893605035cd60e92ad53177f4377237",
        file: "binutils-2.44.tar.xz",
    },
    PinDef {
        key: "bison-mesboot-source",
        aliases: &[],
        // GNU Bison 3.8.2 — the parser generator glibc 2.41's configure requires
        // (>= 2.7, critical; used to regenerate intl/plural.c from plural.y, re
        // #469). Latest 3.x, exactly what live-bootstrap builds. The pristine
        // tarball ships the pre-generated parser/scanner C (src/parse-gram.c,
        // src/scan-gram.c), so no bootstrap bison and no flex are needed to
        // build it. Built at the gcc-14 tier, static; execs m4-mesboot at
        // runtime (M4 baked at configure).
        url: "https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz",
        sha256: "9bba0214ccf7f1079c5d59210045227bcf619519840ebfa80cd3849cff5a5bf2",
        file: "bison-3.8.2.tar.xz",
    },
    PinDef {
        key: "busybox-x86-64-source",
        aliases: &[],
        url: "https://busybox.net/downloads/busybox-1.37.0.tar.bz2",
        sha256: "3311dff32e746499f4df0d5df04d7eb396382d7e108bb9250e7b519b837043a4",
        file: "busybox-1.37.0.tar.bz2",
    },
    PinDef {
        key: "cmake-x86-64-source",
        aliases: &[],
        // CMake is the one explicitly approved new build-only dependency for the
        // Rust bridge (PR #533). LLVM 22 requires CMake >= 3.20; the maintained
        // 3.31 line is new enough without adopting a moving latest release.
        url: "https://cmake.org/files/v3.31/cmake-3.31.12.tar.gz",
        sha256: "5f3fd5a54dfa65602bdbed64f981a72673cc19f2d304cc2955cf0dfa0cfd8272",
        file: "cmake-3.31.12.tar.gz",
    },
    PinDef {
        key: "coreutils-mesboot0-source",
        aliases: &[],
        // GNU coreutils 5.0 — the tcc-era coreutils provider (re #469). The exact
        // version live-bootstrap builds under tcc + mes libc (its coreutils-5.0
        // pass1), a cycle-breaker below the first host-tool consumer.
        url: "https://ftp.gnu.org/gnu/coreutils/coreutils-5.0.tar.bz2",
        sha256: "c25b36b8af6e0ad2a875daf4d6196bd0df28a62be7dd252e5f99a4d5d7288d95",
        file: "coreutils-5.0.tar.bz2",
    },
    PinDef {
        key: "diffutils-mesboot0-source",
        aliases: &[],
        // GNU diffutils 2.7 — the tcc-era `diffutils` provider (re #469). The exact
        // version live-bootstrap builds under tcc + mes libc (its diffutils-2.7
        // step), a cycle-breaker below the first host-tool consumer. Ships `cmp`
        // and `diff`, the last of the five host tools to gain a provider.
        url: "https://ftp.gnu.org/gnu/diffutils/diffutils-2.7.tar.gz",
        sha256: "d5f2489c4056a31528e3ada4adacc23d498532b0af1a980f2f76158162b139d6",
        file: "diffutils-2.7.tar.gz",
    },
    PinDef {
        key: "gawk-mesboot-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gawk/gawk-3.1.8.tar.gz",
        sha256: "2146b3cc7a2d2b16a9457e73f14a3cb51a4292575425ed8f16f7e0a5e4f1a50d",
        file: "gawk-3.1.8.tar.gz",
    },
    PinDef {
        key: "gawk-mesboot0-source",
        aliases: &[],
        // GNU awk 3.0.4 — the tcc-era `gawk` provider (re #469). The exact
        // version live-bootstrap builds under tcc + mes libc (its gawk-3.0.4
        // step), a cycle-breaker below the first host-tool consumer — NOT the
        // heavier gcc-mesboot1-era gawk 3.1.8 the separate `gawk-mesboot` rung
        // uses.
        url: "https://ftp.gnu.org/gnu/gawk/gawk-3.0.4.tar.gz",
        sha256: "5cc35def1ff4375a8b9a98c2ff79e95e80987d24f0d42fdbb7b7039b3ddb3fb0",
        file: "gawk-3.0.4.tar.gz",
    },
    PinDef {
        key: "grep-mesboot0-source",
        aliases: &[],
        // GNU grep 2.4 — the tcc-era grep provider (re #469). The exact version
        // live-bootstrap builds under tcc + mes libc (its grep-2.4 step), a
        // cycle-breaker below the first host-tool consumer.
        url: "https://ftp.gnu.org/gnu/grep/grep-2.4.tar.gz",
        sha256: "a32032bab36208509466654df12f507600dfe0313feebbcd218c32a70bf72a16",
        file: "grep-2.4.tar.gz",
    },
    PinDef {
        key: "gcc-10-bridge-source",
        aliases: &[],
        // GCC 10.5.0 is the compatibility bridge from gcc-mesboot 4.9.4 to
        // GCC 14.3.0. live-bootstrap uses the same release between GCC 4.7.4
        // and its current compiler; keeping it as a declared fixed-output
        // source makes the extra trust/provenance edge explicit and offline.
        url: "https://ftp.gnu.org/gnu/gcc/gcc-10.5.0/gcc-10.5.0.tar.xz",
        sha256: "25109543fdf46f397c347b5d8b7a2c7e5694a5a51cce4b9c6e1ea8a71ca307c1",
        file: "gcc-10.5.0.tar.xz",
    },
    PinDef {
        key: "gcc-14-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-14.3.0/gcc-14.3.0.tar.xz",
        sha256: "e0dc77297625631ac8e50fa92fffefe899a4eb702592da5c32ef04e2293aca3a",
        file: "gcc-14.3.0.tar.xz",
    },
    PinDef {
        key: "gcc-494-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-4.9.4/gcc-4.9.4.tar.bz2",
        sha256: "6c11d292cd01b294f9f84c9a59c230d80e9e4a47e5c6355f046bb36d4f358092",
        file: "gcc-4.9.4.tar.bz2",
    },
    PinDef {
        key: "gcc-core-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-2.95.3/gcc-core-2.95.3.tar.gz",
        sha256: "56811ee60990b4660d54c2a66f5e0253a487e330ee53b499d8a565882ff16ef7",
        file: "gcc-core-2.95.3.tar.gz",
    },
    PinDef {
        key: "gcc-464-core",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-4.6.4/gcc-core-4.6.4.tar.gz",
        sha256: "e534a5cb05ab839d7cf7b2496fd5df42e76352926c1cf0d94de76184c26a739c",
        file: "gcc-core-4.6.4.tar.gz",
    },
    PinDef {
        key: "gcc-464-gpp",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-4.6.4/gcc-g++-4.6.4.tar.gz",
        sha256: "690a5d4f664180640db28079e3461468192c484c37d6f671dde4b53a7f9918bb",
        file: "gcc-g++-4.6.4.tar.gz",
    },
    PinDef {
        key: "gmp63",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz",
        sha256: "a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898",
        file: "gmp-6.3.0.tar.xz",
    },
    PinDef {
        key: "mpc131",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz",
        sha256: "ab642492f5cf882b74aa0cb730cd410a81edcdbec895183ce930e706c1c759b8",
        file: "mpc-1.3.1.tar.gz",
    },
    PinDef {
        key: "mpfr421",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz",
        sha256: "277807353a6726978996945af13e52829e3abd7a9a5b7fb2793894e18f1fcbb2",
        file: "mpfr-4.2.1.tar.xz",
    },
    PinDef {
        key: "glibc-mesboot0-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/glibc/glibc-2.2.5.tar.gz",
        sha256: "58dc8df59aed1e4d9d50eef9e4c4c0789fa283b50f7a093932d0f467424484ee",
        file: "glibc-2.2.5.tar.gz",
    },
    PinDef {
        key: "glibc-241-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/glibc/glibc-2.41.tar.xz",
        sha256: "a5a26b22f545d6b7d7b3dd828e11e428f24f4fac43c934fb071b6a7d0828e901",
        file: "glibc-2.41.tar.xz",
    },
    PinDef {
        key: "glibc-216-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/glibc/glibc-2.16.0.tar.gz",
        sha256: "a75be51658cc1cfb6324ec6dbdbed416526c44c14814823129f0fcc74c279f6e",
        file: "glibc-2.16.0.tar.gz",
    },
    PinDef {
        key: "gmp",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gmp/gmp-4.3.2.tar.gz",
        sha256: "7be3ad1641b99b17f6a8be6a976f1f954e997c41e919ad7e0c418fe848c13c97",
        file: "gmp-4.3.2.tar.gz",
    },
    PinDef {
        key: "gzip-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gzip/gzip-1.2.4.tar",
        sha256: "4d2ce9f314f39c9575f913503b0178d6fb2c92920db8e7b7b176b7bab7980fe6",
        file: "gzip-1.2.4.tar",
    },
    PinDef {
        key: "hello-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz",
        sha256: "31e066137a962676e89f69d1b65382de95a7ef7d914b8cb956f41ea72e0f516b",
        file: "hello-2.10.tar.gz",
    },
    PinDef {
        key: "linux-source",
        aliases: &["linux-headers", "linux-headers-x86-64"],
        url: "https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.14.67.tar.xz",
        sha256: "3f4b056dc27233a78f7a4a35ed6fdcfd0a9680ec40b611a898bb6c8b905070ba",
        file: "linux-4.14.67.tar.xz",
    },
    PinDef {
        key: "m4-mesboot-source",
        aliases: &[],
        // GNU M4 1.4.19 — the macro processor the glibc-rung `bison` provider
        // needs at build and runtime (re #469). Latest stable; the release
        // tarball ships pre-generated files so no host m4/autotools are needed
        // to build it (m4 does not require m4 to bootstrap). Built at the
        // gcc-14 tier, static against glibc-mesboot, like every glibc-rung
        // build tool.
        url: "https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz",
        sha256: "63aede5c6d33b6d9b13511cd0be2cac046f2e70fd0a07aa9573a04a82783af96",
        file: "m4-1.4.19.tar.xz",
    },
    PinDef {
        key: "make-mesboot0-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/make/make-3.80.tar.gz",
        sha256: "64b30b41fde2ebf669e6af489883fb1df6a06ac30555a96cfa3c39ecce7267dd",
        file: "make-3.80.tar.gz",
    },
    PinDef {
        key: "make-mesboot-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/make/make-3.82.tar.gz",
        sha256: "3d991b33e604187c5881a0abc2e102d5b9776da5569640e73778f85d617242e7",
        file: "make-3.82.tar.gz",
    },
    PinDef {
        key: "make-x86-64-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz",
        sha256: "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3",
        file: "make-4.4.1.tar.gz",
    },
    PinDef {
        key: "mes-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mes/mes-0.27.1.tar.gz",
        sha256: "183a40ea47ea49f8a1e3bd1b9d12e676374d64d63bc79e7bc1ae7d673dfdf25d",
        file: "mes-0.27.1.tar.gz",
    },
    PinDef {
        key: "mpc",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz",
        sha256: "617decc6ea09889fb08ede330917a00b16809b8db88c29c31bfbb49cbf88ecc3",
        file: "mpc-1.0.3.tar.gz",
    },
    PinDef {
        key: "mpfr",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mpfr/mpfr-2.4.2.tar.gz",
        sha256: "246d7e184048b1fc48d3696dd302c9774e24e921204221540745e5464022b637",
        file: "mpfr-2.4.2.tar.gz",
    },
    PinDef {
        key: "nyacc",
        aliases: &[],
        url: "https://download.savannah.nongnu.org/releases/nyacc/nyacc-1.00.2.tar.gz",
        sha256: "f36e4fb7dd524dc3f4b354d3d5313f69e7ce5a6ae93711e8cf6d51eaa8d2b318",
        file: "nyacc-1.00.2.tar.gz",
    },
    PinDef {
        key: "oyacc-source",
        aliases: &[],
        // OpenBSD yacc, portable release (ibara/yacc). Same version live-bootstrap
        // builds under tcc+mes-libc to regenerate bash's parser (re #469).
        url: "https://github.com/ibara/yacc/releases/download/oyacc-6.6/oyacc-6.6.tar.gz",
        sha256: "eb0866e740b79bd3a23e0ca47885eb3148aab18d77a4bedba96e979d8b4ebfe1",
        file: "oyacc-6.6.tar.gz",
    },
    PinDef {
        key: "patch-mesboot-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/patch/patch-2.5.9.tar.gz",
        sha256: "ecb5c6469d732bcf01d6ec1afe9e64f1668caba5bfdb103c28d7f537ba3cdb8a",
        file: "patch-2.5.9.tar.gz",
    },
    PinDef {
        key: "python-mesboot-source",
        aliases: &[],
        // CPython 3.11.1 — the python3 glibc 2.41's configure requires (>= 3.4,
        // critical; scripts/gen-as-const.py generates core headers, re #469).
        // Exactly what live-bootstrap builds. A NATIVE (build==host) build needs
        // NO pre-existing python: CPython's C tools _freeze_module +
        // _bootstrap_python generate the frozen/deepfreeze sources during the
        // build. Minimal: only the always-built C modules (no ssl/zlib/ffi),
        // which is all gen-as-const.py imports (argparse/re/subprocess/…). Built
        // at the gcc-14 tier vs the shared glibc 2.16.0 (glibc-mesboot-shared).
        url: "https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tar.xz",
        sha256: "85879192f2cffd56cb16c092905949ebf3e5e394b7f764723529637901dfb58f",
        file: "Python-3.11.1.tar.xz",
    },
    PinDef {
        key: "rust-source",
        aliases: &[],
        // The upstream source release is comprehensive: vendored Cargo sources,
        // in-tree Cargo, and llvm-project are all inside this fixed-output input.
        url: "https://static.rust-lang.org/dist/rustc-1.96.0-src.tar.xz",
        sha256: "b99ce16cdf0ecfc761b585ac84d131b46733465a02f8ecd0ff2de9713c62ee09",
        file: "rustc-1.96.0-src.tar.xz",
    },
    PinDef {
        key: "rust-stage0-rustc-source",
        aliases: &[],
        // Exact bootstrap compiler selected by rustc 1.96.0's src/stage0.
        url: "https://static.rust-lang.org/dist/2026-04-16/rustc-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
        sha256: "8426a3d170a5879f5682f5fbdd024a1779b3951e7baba685af2d6dc32a6dfc15",
        file: "rustc-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
    },
    PinDef {
        key: "rust-stage0-std-source",
        aliases: &[],
        url: "https://static.rust-lang.org/dist/2026-04-16/rust-std-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
        sha256: "047ea7098803d3500fa1072e9cee5392697e21525559e4458128a2bf874aa382",
        file: "rust-std-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
    },
    PinDef {
        key: "rust-stage0-cargo-source",
        aliases: &[],
        url: "https://static.rust-lang.org/dist/2026-04-16/cargo-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
        sha256: "e74edd2cf7d0f1f1383b4f00eb90c843750bc489e2ccf7214e6476678a907425",
        file: "cargo-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
    },
    PinDef {
        key: "sed-mesboot-source",
        aliases: &[],
        // GNU sed 4.2.2 — the from-source `sed` provider (re #469), a sibling of
        // the gawk-mesboot rung: gcc-mesboot1 + glibc-mesboot0 build it exactly as
        // gawk 3.1.8 is built one tier down. Its gnulib papers over glibc 2.2.5
        // gaps the same way gawk's does, so no host `sed` need leak onto a rung
        // that can reach this output.
        url: "https://ftp.gnu.org/gnu/sed/sed-4.2.2.tar.gz",
        sha256: "fea0a94d4b605894f3e2d5572e3f96e4413bcad3a085aae7367c2cf07908b2ff",
        file: "sed-4.2.2.tar.gz",
    },
    PinDef {
        key: "sed-mesboot0-source",
        aliases: &[],
        // GNU sed 4.0.9 — the tcc-era `sed` provider (re #469). The exact
        // version live-bootstrap builds under tcc + mes libc (its LIBC=mes mk
        // branch), a cycle-breaker below the first host-tool consumer. NOT the
        // heavier sed 4.2.2 the gcc-mesboot1-era `sed-mesboot` rung uses.
        url: "https://ftp.gnu.org/gnu/sed/sed-4.0.9.tar.gz",
        sha256: "c365874794187f8444e5d22998cd5888ffa47f36def4b77517a808dec27c0600",
        file: "sed-4.0.9.tar.gz",
    },
    PinDef {
        key: "stage0-source",
        aliases: &[],
        url: "https://github.com/oriansj/stage0-posix/releases/download/Release_1.9.1/stage0-posix-1.9.1.tar.gz",
        sha256: "f4fdda675de90ab034fd3467ef43cddff61b3d372f8e0e5c2d25d145f224226f",
        file: "stage0-posix-1.9.1.tar.gz",
    },
    PinDef {
        key: "tcc-source",
        aliases: &[],
        url: "https://lilypond.org/janneke/tcc/tcc-0.9.26-1149-g46a75d0c.tar.gz",
        sha256: "f4f6ce121ac631a234af080753fb9d645d2334d20160b37abbe75b574a1e1d19",
        file: "tcc-0.9.26-1149-g46a75d0c.tar.gz",
    },
    PinDef {
        key: "tcc-0.9.27-source",
        aliases: &[],
        url: "https://download.savannah.nongnu.org/releases/tinycc/tcc-0.9.27.tar.bz2",
        sha256: "de23af78fca90ce32dff2dd45b3432b2334740bb9bb7b05bf60fdbfc396ceb9c",
        file: "tcc-0.9.27.tar.bz2",
    },
    PinDef {
        key: "zlib-x86-64-source",
        aliases: &[],
        url: "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz",
        sha256: "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23",
        file: "zlib-1.3.1.tar.gz",
    },
];

pub fn all() -> Vec<SourcePin> {
    PINS.iter().map(|pin| materialize(pin, pin.key)).collect()
}

pub fn by_key(key: &str) -> Option<SourcePin> {
    PINS.iter()
        .find(|pin| pin.key == key || pin.aliases.iter().any(|alias| *alias == key))
        .map(|pin| materialize(pin, key))
}

fn materialize(pin: &PinDef, key: &str) -> SourcePin {
    SourcePin::new(key, pin.url, pin.sha256, pin.file)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_carries_all_legacy_source_locks() {
        // 32 migrated legacy locks + oyacc-6.6 (the from-source `yacc`) +
        // bash-2.05b (the from-source bootstrap shell it regenerates, re #469) +
        // sed-4.2.2 (the gcc-mesboot1-era `sed` provider, re #469) +
        // sed-4.0.9 (the tcc-era `sed` cycle-breaker, re #469) +
        // coreutils-5.0 (the tcc-era coreutils cycle-breaker, re #469) +
        // grep-2.4 (the tcc-era `grep` cycle-breaker, re #469) +
        // gawk-3.0.4 (the tcc-era `gawk` cycle-breaker, re #469) +
        // diffutils-2.7 (the tcc-era `diffutils` cycle-breaker, re #469) +
        // m4-1.4.19 (the glibc-rung `bison` provider's macro processor, re #469) +
        // bison-3.8.2 (the glibc-rung parser generator, re #469) +
        // Python-3.11.1 (the glibc-rung python3, re #469) + GCC 10.5.0 (the
        // compatibility bridge between gcc-mesboot 4.9.4 and GCC 14.3.0) +
        // CMake 3.31.12 + Rust 1.96.0 source and its exact three-component
        // Rust 1.95.0 bootstrap snapshot.
        assert_eq!(all().len(), 48);
    }

    #[test]
    fn linux_header_inputs_resolve_to_the_linux_source_pin() {
        let linux = by_key("linux-headers-x86-64").unwrap();
        assert_eq!(linux.file, "linux-4.14.67.tar.xz");
        assert_eq!(linux.key, "linux-headers-x86-64");
    }
}
