//! Fixed-output source pins owned by the recipe catalog.
//!
//! This replaces the old external source lock directory. The keys are the
//! staged input names recipes declare through `source_input(...)` or `inputs`.

use crate::types::SourcePin;

struct PinDef {
    key: &'static str,
    aliases: &'static [&'static str],
    url: &'static str,
    sha256: &'static str,
    file: &'static str,
}

const PINS: &[PinDef] = &[
    PinDef {
        key: "abseil-cpp-x86-64-source",
        aliases: &[],
        // Protobuf 31.1's build declares this exact Abseil release. It is
        // staged as source data and consumed through CMake's local
        // FetchContent override; the build never invokes a network transport.
        url: "https://github.com/abseil/abseil-cpp/releases/download/20250127.0/abseil-cpp-20250127.0.tar.gz",
        sha256: "16242f394245627e508ec6bb296b433c90f8d914f73b9c026fddb905e27276e8",
        file: "abseil-cpp-20250127.0.tar.gz",
    },
    PinDef {
        key: "bash-mesboot-source",
        aliases: &[],
        // GNU bash 2.05b — the from-source bootstrap shell (re #469). Same
        // version live-bootstrap builds under tcc + mes libc (its parser
        // regenerated by the oyacc rung's `yacc`) to replace the host bash.
        url: "https://ftp.gnu.org/gnu/bash/bash-2.05b.tar.gz",
        sha256: "ba03d412998cc54bd0b0f2d6c32100967d3137098affdc2d32e6e7c11b163fe4",
        file: "bash-2.05b.tar.gz",
    },
    PinDef {
        key: "binutils-mesboot-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/binutils/binutils-2.20.1a.tar.bz2",
        sha256: "71d37c96451333c5c0b84b170169fdcb138bbb27397dc06281905d9717c8ed64",
        file: "binutils-2.20.1a.tar.bz2",
    },
    PinDef {
        key: "binutils-244-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/binutils/binutils-2.44.tar.xz",
        sha256: "ce2017e059d63e67ddb9240e9d4ec49c2893605035cd60e92ad53177f4377237",
        file: "binutils-2.44.tar.xz",
    },
    PinDef {
        key: "bison-mesboot-source",
        aliases: &[],
        // GNU Bison 3.8.2 — the parser generator glibc 2.41's configure requires
        // (>= 2.7, critical; used to regenerate intl/plural.c from plural.y, re
        // #469). Latest 3.x, exactly what live-bootstrap builds. The pristine
        // tarball ships the pre-generated parser/scanner C (src/parse-gram.c,
        // src/scan-gram.c), so no bootstrap bison and no flex are needed to
        // build it. Built at the gcc-14 tier, static; execs m4-mesboot at
        // runtime (M4 baked at configure).
        url: "https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz",
        sha256: "9bba0214ccf7f1079c5d59210045227bcf619519840ebfa80cd3849cff5a5bf2",
        file: "bison-3.8.2.tar.xz",
    },
    PinDef {
        key: "btrfs-progs-x86-64-source",
        aliases: &[],
        // btrfs-progs 7.0 provides the offline --rootdir/--subvol image builder
        // used to initialize persistent system volumes without host mounts.
        url: "https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v7.0.tar.xz",
        sha256: "c286d6876cbcd72327a0b417e4cfd280353ec23e37b549fdbcd7800a832d9a99",
        file: "btrfs-progs-v7.0.tar.xz",
    },
    PinDef {
        key: "busybox-x86-64-source",
        aliases: &[],
        url: "https://busybox.net/downloads/busybox-1.37.0.tar.bz2",
        sha256: "3311dff32e746499f4df0d5df04d7eb396382d7e108bb9250e7b519b837043a4",
        file: "busybox-1.37.0.tar.bz2",
    },
    PinDef {
        key: "ca-certificates-source",
        aliases: &[],
        // Mozilla's trust store as rendered in PEM form by curl. Pin the dated
        // extract rather than curl's moving cacert.pem URL so a reviewed update
        // changes both the source name and its published adjacent SHA-256.
        url: "https://curl.se/ca/cacert-2026-08-13.pem",
        sha256: "f66dff1bdf8f96060b8177976f8b7d9254bc89bc4db933d769f7384d28480bc9",
        file: "cacert-2026-08-13.pem",
    },
    PinDef {
        key: "cmake-x86-64-source",
        aliases: &[],
        // CMake is the one explicitly approved new build-only dependency for the
        // Rust bridge (PR #533). LLVM 22 requires CMake >= 3.20; the maintained
        // 3.31 line is new enough without adopting a moving latest release.
        url: "https://cmake.org/files/v3.31/cmake-3.31.12.tar.gz",
        sha256: "5f3fd5a54dfa65602bdbed64f981a72673cc19f2d304cc2955cf0dfa0cfd8272",
        file: "cmake-3.31.12.tar.gz",
    },
    PinDef {
        key: "codex-cargo-crossterm-source",
        aliases: &[],
        // Cargo pins this fork by its full commit. The fixed-output archive is
        // source data only: td's Rust runner vendors it without invoking Git.
        url: "https://github.com/openai-oss-forks/crossterm/archive/45fecb9508105988f42fe6ff0441783ed3717f92.tar.gz",
        sha256: "408decc2710285f01e6a154e2605891e1af297961fd4e6517dcbfb9491eb6c6f",
        file: "codex-crossterm-45fecb9508105988f42fe6ff0441783ed3717f92.tar.gz",
    },
    PinDef {
        key: "codex-cargo-nucleo-source",
        aliases: &[],
        url: "https://github.com/helix-editor/nucleo/archive/4253de9faabb4e5c6d81d946a5e35a90f87347ee.tar.gz",
        sha256: "d1676ac33a82c5903ffede68ce73c9d924666aa8a102bb649a8fb926a7a61ce1",
        file: "codex-nucleo-4253de9faabb4e5c6d81d946a5e35a90f87347ee.tar.gz",
    },
    PinDef {
        key: "codex-cargo-rules-rust-source",
        aliases: &[],
        url: "https://github.com/dzbarsky/rules_rust/archive/b56cbaa8465e74127f1ea216f813cd377295ad81.tar.gz",
        sha256: "ddbdf40db8df685df67c3260dfe59cf7ffa4b193a9324e10b359bbe8981db9e0",
        file: "codex-rules-rust-b56cbaa8465e74127f1ea216f813cd377295ad81.tar.gz",
    },
    PinDef {
        key: "codex-cargo-tokio-tungstenite-source",
        aliases: &[],
        url: "https://github.com/openai-oss-forks/tokio-tungstenite/archive/0e5b2d73aa18dd9f0a50ee9ff199d5aef7594186.tar.gz",
        sha256: "a1d8bfedf41ea59d5ed375ebc280dad7099d0c3398e91406c51d485270196a3d",
        file: "codex-tokio-tungstenite-0e5b2d73aa18dd9f0a50ee9ff199d5aef7594186.tar.gz",
    },
    PinDef {
        key: "codex-cargo-tungstenite-source",
        aliases: &[],
        url: "https://github.com/openai-oss-forks/tungstenite-rs/archive/4fffad30fe373adbdcffab9545e9e9bf4f2fc19f.tar.gz",
        sha256: "d85393467dd5843688059bb204a61b7450dce1166a2c8aab3c87478955ffce48",
        file: "codex-tungstenite-4fffad30fe373adbdcffab9545e9e9bf4f2fc19f.tar.gz",
    },
    PinDef {
        key: "codex-source",
        aliases: &[],
        // OpenAI Codex 0.148.0 is the source-built daily-driver coding agent.
        // The same reviewed archive supplies its vendored Bubblewrap 0.11.2
        // sources; the helper is compiled separately against td-built libcap.
        // Upstream publishes binaries but no source release asset for this tag;
        // GitHub's tag archive is its only upstream-hosted source archive, so
        // this exact SHA pin deliberately accepts that availability tradeoff.
        url: "https://github.com/openai/codex/archive/refs/tags/rust-v0.148.0.tar.gz",
        sha256: "a45e90403eb36b7d6093b167fe1c7dba9b36063bef6d39359eed52c47a21f94a",
        file: "codex-rust-v0.148.0.tar.gz",
    },
    PinDef {
        key: "coreutils-mesboot0-source",
        aliases: &[],
        // GNU coreutils 5.0 — the tcc-era coreutils provider (re #469). The exact
        // version live-bootstrap builds under tcc + mes libc (its coreutils-5.0
        // pass1), a cycle-breaker below the first host-tool consumer.
        url: "https://ftp.gnu.org/gnu/coreutils/coreutils-5.0.tar.bz2",
        sha256: "c25b36b8af6e0ad2a875daf4d6196bd0df28a62be7dd252e5f99a4d5d7288d95",
        file: "coreutils-5.0.tar.bz2",
    },
    PinDef {
        key: "curl-x86-64-source",
        aliases: &[],
        // curl 8.21.0 supplies Git's source-built HTTP/HTTPS transport. The
        // recipe keeps only static libcurl and disables every protocol and
        // optional dependency outside the reviewed HTTP(S) closure.
        url: "https://curl.se/download/curl-8.21.0.tar.xz",
        sha256: "aa1b66a70eace83dc624508745646c08ae561de512ab403adffb93ac87fc72e6",
        file: "curl-8.21.0.tar.xz",
    },
    PinDef {
        key: "diffutils-mesboot0-source",
        aliases: &[],
        // GNU diffutils 2.7 — the tcc-era `diffutils` provider (re #469). The exact
        // version live-bootstrap builds under tcc + mes libc (its diffutils-2.7
        // step), a cycle-breaker below the first host-tool consumer. Ships `cmp`
        // and `diff`, the last of the five host tools to gain a provider.
        url: "https://ftp.gnu.org/gnu/diffutils/diffutils-2.7.tar.gz",
        sha256: "d5f2489c4056a31528e3ada4adacc23d498532b0af1a980f2f76158162b139d6",
        file: "diffutils-2.7.tar.gz",
    },
    PinDef {
        key: "elfutils-x86-64-source",
        aliases: &[],
        // elfutils 0.192 — the source of `libelf`, which the modern Linux kernel's
        // objtool host tool links against (re #529). objtool is force-selected on
        // x86_64 in current kernels (7.x: HAVE_STATIC_CALL_INLINE +
        // HAVE_UACCESS_VALIDATION both `select OBJTOOL` unconditionally), so libelf
        // is not avoidable the way it was in the 4.14 rung. The `elfutils-x86-64` recipe builds ONLY libelf.a
        // + headers from this tarball with td's native x86_64 toolchain; objtool
        // tolerates old libelf (it defines LIBELF_USE_DEPRECATED), so the exact
        // version is not load-bearing. 0.192 is a deliberate stable pin (a
        // reviewed update bumps the version + hash together); newer 0.19x
        // releases exist and any of them would serve — this is not a "latest"
        // claim, and the build asserts nothing about the minor version.
        url: "https://sourceware.org/elfutils/ftp/0.192/elfutils-0.192.tar.bz2",
        sha256: "616099beae24aba11f9b63d86ca6cc8d566d968b802391334c91df54eab416b4",
        file: "elfutils-0.192.tar.bz2",
    },
    PinDef {
        key: "fd-source",
        aliases: &[],
        url: "https://static.crates.io/crates/fd-find/fd-find-10.2.0.crate",
        sha256: "de08defa195af894cc295a43bfc65ba28903e492fd5f32f7a24bf75eafd9bf34",
        file: "fd-find-10.2.0.crate",
    },
    PinDef {
        key: "flex-x86-64-source",
        aliases: &[],
        // GNU flex 2.6.4 — the lexical-analyzer generator the modern Linux kernel
        // (>= 4.18) requires for scripts/kconfig's lexer; the pre-generated
        // `*_shipped` parsers the 4.14 rung relied on are gone from the current
        // tree (re #529). The `flex-x86-64` recipe builds it static with td's
        // native x86_64 toolchain. The release tarball ships the generated
        // scanner/parser C (src/scan.c, src/parse.c), so no pre-existing flex or
        // bison is needed to build it; it execs m4 (m4-mesboot, baked at configure)
        // at scanner-generation time. Latest release.
        url: "https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz",
        sha256: "e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995",
        file: "flex-2.6.4.tar.gz",
    },
    PinDef {
        key: "gawk-mesboot-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gawk/gawk-3.1.8.tar.gz",
        sha256: "2146b3cc7a2d2b16a9457e73f14a3cb51a4292575425ed8f16f7e0a5e4f1a50d",
        file: "gawk-3.1.8.tar.gz",
    },
    PinDef {
        key: "gawk-mesboot0-source",
        aliases: &[],
        // GNU awk 3.0.4 — the tcc-era `gawk` provider (re #469). The exact
        // version live-bootstrap builds under tcc + mes libc (its gawk-3.0.4
        // step), a cycle-breaker below the first host-tool consumer — NOT the
        // heavier gcc-mesboot1-era gawk 3.1.8 the separate `gawk-mesboot` rung
        // uses.
        url: "https://ftp.gnu.org/gnu/gawk/gawk-3.0.4.tar.gz",
        sha256: "5cc35def1ff4375a8b9a98c2ff79e95e80987d24f0d42fdbb7b7039b3ddb3fb0",
        file: "gawk-3.0.4.tar.gz",
    },
    PinDef {
        key: "grep-mesboot0-source",
        aliases: &[],
        // GNU grep 2.4 — the tcc-era grep provider (re #469). The exact version
        // live-bootstrap builds under tcc + mes libc (its grep-2.4 step), a
        // cycle-breaker below the first host-tool consumer.
        url: "https://ftp.gnu.org/gnu/grep/grep-2.4.tar.gz",
        sha256: "a32032bab36208509466654df12f507600dfe0313feebbcd218c32a70bf72a16",
        file: "grep-2.4.tar.gz",
    },
    PinDef {
        key: "git-x86-64-source",
        aliases: &[],
        // Git 2.55.0 is the source-built daily-driver client. Its initial td
        // configuration keeps local repositories and HTTP(S) remotes while
        // omitting language runtimes, SSH, WebDAV, and direct OpenSSL use.
        url: "https://www.kernel.org/pub/software/scm/git/git-2.55.0.tar.xz",
        sha256: "457fdb04dc8728e007d4688695e6912e6f680727920f2a40bf11eacc17505357",
        file: "git-2.55.0.tar.xz",
    },
    PinDef {
        key: "gcc-10-bridge-source",
        aliases: &[],
        // GCC 10.5.0 is the compatibility bridge from gcc-mesboot 4.9.4 to
        // GCC 14.3.0. live-bootstrap uses the same release between GCC 4.7.4
        // and its current compiler; keeping it as a declared fixed-output
        // source makes the extra trust/provenance edge explicit and offline.
        url: "https://ftp.gnu.org/gnu/gcc/gcc-10.5.0/gcc-10.5.0.tar.xz",
        sha256: "25109543fdf46f397c347b5d8b7a2c7e5694a5a51cce4b9c6e1ea8a71ca307c1",
        file: "gcc-10.5.0.tar.xz",
    },
    PinDef {
        key: "gcc-14-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-14.3.0/gcc-14.3.0.tar.xz",
        sha256: "e0dc77297625631ac8e50fa92fffefe899a4eb702592da5c32ef04e2293aca3a",
        file: "gcc-14.3.0.tar.xz",
    },
    PinDef {
        key: "gcc-494-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-4.9.4/gcc-4.9.4.tar.bz2",
        sha256: "6c11d292cd01b294f9f84c9a59c230d80e9e4a47e5c6355f046bb36d4f358092",
        file: "gcc-4.9.4.tar.bz2",
    },
    PinDef {
        key: "gcc-core-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-2.95.3/gcc-core-2.95.3.tar.gz",
        sha256: "56811ee60990b4660d54c2a66f5e0253a487e330ee53b499d8a565882ff16ef7",
        file: "gcc-core-2.95.3.tar.gz",
    },
    PinDef {
        key: "gcc-464-core",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-4.6.4/gcc-core-4.6.4.tar.gz",
        sha256: "e534a5cb05ab839d7cf7b2496fd5df42e76352926c1cf0d94de76184c26a739c",
        file: "gcc-core-4.6.4.tar.gz",
    },
    PinDef {
        key: "gcc-464-gpp",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gcc/gcc-4.6.4/gcc-g++-4.6.4.tar.gz",
        sha256: "690a5d4f664180640db28079e3461468192c484c37d6f671dde4b53a7f9918bb",
        file: "gcc-g++-4.6.4.tar.gz",
    },
    PinDef {
        key: "gmp63",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz",
        sha256: "a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898",
        file: "gmp-6.3.0.tar.xz",
    },
    PinDef {
        key: "mpc131",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz",
        sha256: "ab642492f5cf882b74aa0cb730cd410a81edcdbec895183ce930e706c1c759b8",
        file: "mpc-1.3.1.tar.gz",
    },
    PinDef {
        key: "mpfr421",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz",
        sha256: "277807353a6726978996945af13e52829e3abd7a9a5b7fb2793894e18f1fcbb2",
        file: "mpfr-4.2.1.tar.xz",
    },
    PinDef {
        key: "glibc-mesboot0-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/glibc/glibc-2.2.5.tar.gz",
        sha256: "58dc8df59aed1e4d9d50eef9e4c4c0789fa283b50f7a093932d0f467424484ee",
        file: "glibc-2.2.5.tar.gz",
    },
    PinDef {
        key: "glibc-241-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/glibc/glibc-2.41.tar.xz",
        sha256: "a5a26b22f545d6b7d7b3dd828e11e428f24f4fac43c934fb071b6a7d0828e901",
        file: "glibc-2.41.tar.xz",
    },
    PinDef {
        key: "glibc-216-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/glibc/glibc-2.16.0.tar.gz",
        sha256: "a75be51658cc1cfb6324ec6dbdbed416526c44c14814823129f0fcc74c279f6e",
        file: "glibc-2.16.0.tar.gz",
    },
    PinDef {
        key: "gmp",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gmp/gmp-4.3.2.tar.gz",
        sha256: "7be3ad1641b99b17f6a8be6a976f1f954e997c41e919ad7e0c418fe848c13c97",
        file: "gmp-4.3.2.tar.gz",
    },
    PinDef {
        key: "gzip-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/gzip/gzip-1.2.4.tar",
        sha256: "4d2ce9f314f39c9575f913503b0178d6fb2c92920db8e7b7b176b7bab7980fe6",
        file: "gzip-1.2.4.tar",
    },
    PinDef {
        key: "hello-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz",
        sha256: "31e066137a962676e89f69d1b65382de95a7ef7d914b8cb956f41ea72e0f516b",
        file: "hello-2.10.tar.gz",
    },
    PinDef {
        key: "libcap-x86-64-source",
        aliases: &[],
        // libcap 2.78 is the small static capability-name library required by
        // Codex's vendored Bubblewrap. Only libcap.a and its public headers
        // leave the recipe; no administrative tools or shared objects ship.
        url: "https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.78.tar.xz",
        sha256: "0d621e562fd932ccf67b9660fb018e468a683d7b827541df27813228c996bb11",
        file: "libcap-2.78.tar.xz",
    },
    PinDef {
        key: "libressl-x86-64-source",
        aliases: &[],
        // LibreSSL 4.3.2 supplies the OpenSSL-compatible TLS implementation
        // for curl and Git. The recipe builds only static archives and disables
        // upstream assembly so every eventual shipped instruction remains on
        // td's checked frame-pointer path.
        url: "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-4.3.2.tar.gz",
        sha256: "edf01aee24c65d69e6a9efcb9d44bcda682ff9d4f3bbbd95e794e1dfa90847b5",
        file: "libressl-4.3.2.tar.gz",
    },
    PinDef {
        key: "linux-source",
        // The 4.14.67 tree stays pinned ONLY as the source of the UAPI kernel
        // headers (`linux-headers` / `linux-headers-x86-64`) that the whole
        // glibc/gcc toolchain ladder builds against — a stable, ancient-glibc-safe
        // header set. The bootable kernel is a SEPARATE, current pin
        // (`linux-kernel-source`): bumping this one would rebuild the entire
        // toolchain and risk breaking glibc 2.2.5 / 2.16.0 against modern headers.
        aliases: &["linux-headers", "linux-headers-x86-64"],
        url: "https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.14.67.tar.xz",
        sha256: "3f4b056dc27233a78f7a4a35ed6fdcfd0a9680ec40b611a898bb6c8b905070ba",
        file: "linux-4.14.67.tar.xz",
    },
    PinDef {
        key: "linux-kernel-source",
        aliases: &[],
        // Linux 7.1.4 — the latest STABLE mainline kernel (not a longterm/LTS
        // line) the `linux-x86-64` rung source-builds into a bootable x86_64
        // `vmlinux` with td's native toolchain (re #529). DISTINCT from the
        // `linux-source` pin above: this is the full kernel tree to compile, kept
        // current; that one is the frozen 4.14 UAPI-header source for the
        // toolchain. Keeping them separate confines a kernel bump to this one rung
        // instead of the whole ladder. A reviewed update bumps version + sha256 +
        // the seed-digests.txt row together.
        url: "https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.1.4.tar.xz",
        sha256: "1c63922a119675d38e3ae0f8f6ee07f15c41a786ab9ed66563749bb8c9a08e2e",
        file: "linux-7.1.4.tar.xz",
    },
    PinDef {
        key: "m4-mesboot-source",
        aliases: &[],
        // GNU M4 1.4.19 — the macro processor the glibc-rung `bison` provider
        // needs at build and runtime (re #469). Latest stable; the release
        // tarball ships pre-generated files so no host m4/autotools are needed
        // to build it (m4 does not require m4 to bootstrap). Built at the
        // gcc-14 tier, static against glibc-mesboot, like every glibc-rung
        // build tool.
        url: "https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz",
        sha256: "63aede5c6d33b6d9b13511cd0be2cac046f2e70fd0a07aa9573a04a82783af96",
        file: "m4-1.4.19.tar.xz",
    },
    PinDef {
        key: "make-mesboot0-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/make/make-3.80.tar.gz",
        sha256: "64b30b41fde2ebf669e6af489883fb1df6a06ac30555a96cfa3c39ecce7267dd",
        file: "make-3.80.tar.gz",
    },
    PinDef {
        key: "make-mesboot-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/make/make-3.82.tar.gz",
        sha256: "3d991b33e604187c5881a0abc2e102d5b9776da5569640e73778f85d617242e7",
        file: "make-3.82.tar.gz",
    },
    PinDef {
        key: "make-x86-64-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz",
        sha256: "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3",
        file: "make-4.4.1.tar.gz",
    },
    PinDef {
        key: "mes-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mes/mes-0.27.1.tar.gz",
        sha256: "183a40ea47ea49f8a1e3bd1b9d12e676374d64d63bc79e7bc1ae7d673dfdf25d",
        file: "mes-0.27.1.tar.gz",
    },
    PinDef {
        key: "mpc",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz",
        sha256: "617decc6ea09889fb08ede330917a00b16809b8db88c29c31bfbb49cbf88ecc3",
        file: "mpc-1.0.3.tar.gz",
    },
    PinDef {
        key: "mpfr",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/mpfr/mpfr-2.4.2.tar.gz",
        sha256: "246d7e184048b1fc48d3696dd302c9774e24e921204221540745e5464022b637",
        file: "mpfr-2.4.2.tar.gz",
    },
    PinDef {
        key: "nyacc",
        aliases: &[],
        url: "https://download.savannah.nongnu.org/releases/nyacc/nyacc-1.00.2.tar.gz",
        sha256: "f36e4fb7dd524dc3f4b354d3d5313f69e7ce5a6ae93711e8cf6d51eaa8d2b318",
        file: "nyacc-1.00.2.tar.gz",
    },
    PinDef {
        key: "oyacc-source",
        aliases: &[],
        // OpenBSD yacc, portable release (ibara/yacc). Same version live-bootstrap
        // builds under tcc+mes-libc to regenerate bash's parser (re #469).
        url: "https://github.com/ibara/yacc/releases/download/oyacc-6.6/oyacc-6.6.tar.gz",
        sha256: "eb0866e740b79bd3a23e0ca47885eb3148aab18d77a4bedba96e979d8b4ebfe1",
        file: "oyacc-6.6.tar.gz",
    },
    PinDef {
        key: "patch-mesboot-source",
        aliases: &[],
        url: "https://ftp.gnu.org/gnu/patch/patch-2.5.9.tar.gz",
        sha256: "ecb5c6469d732bcf01d6ec1afe9e64f1668caba5bfdb103c28d7f537ba3cdb8a",
        file: "patch-2.5.9.tar.gz",
    },
    PinDef {
        key: "python-mesboot-source",
        aliases: &[],
        // CPython 3.11.1 — the python3 glibc 2.41's configure requires (>= 3.4,
        // critical; scripts/gen-as-const.py generates core headers, re #469).
        // Exactly what live-bootstrap builds. A NATIVE (build==host) build needs
        // NO pre-existing python: CPython's C tools _freeze_module +
        // _bootstrap_python generate the frozen/deepfreeze sources during the
        // build. Minimal: only the always-built C modules (no ssl/zlib/ffi),
        // which is all gen-as-const.py imports (argparse/re/subprocess/…). Built
        // at the gcc-14 tier vs the shared glibc 2.16.0 (glibc-mesboot-shared).
        url: "https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tar.xz",
        sha256: "85879192f2cffd56cb16c092905949ebf3e5e394b7f764723529637901dfb58f",
        file: "Python-3.11.1.tar.xz",
    },
    PinDef {
        key: "protobuf-x86-64-source",
        aliases: &[],
        // Codex's code-mode build script needs protoc 31.1. Build it from the
        // official Protobuf source instead of executing protoc-bin-vendored's
        // target prebuilt payload during the source bootstrap.
        url: "https://github.com/protocolbuffers/protobuf/releases/download/v31.1/protobuf-31.1.tar.gz",
        sha256: "12bfd76d27b9ac3d65c00966901609e020481b9474ef75c7ff4601ac06fa0b82",
        file: "protobuf-31.1.tar.gz",
    },
    PinDef {
        key: "ripgrep-seed-source",
        aliases: &[],
        // The upstream x86-64 musl release is a static PIE and is admitted only
        // as the first sandboxed-application seed. It is never a build tool.
        url: "https://github.com/BurntSushi/ripgrep/releases/download/15.2.0/ripgrep-15.2.0-x86_64-unknown-linux-musl.tar.gz",
        sha256: "33e15bcf1624b25cdd2a55813a47a2f95dbe126268203e76aa6a585d1e7b149c",
        file: "ripgrep-15.2.0-x86_64-unknown-linux-musl.tar.gz",
    },
    PinDef {
        key: "ripgrep-source",
        aliases: &[],
        url: "https://static.crates.io/crates/ripgrep/ripgrep-14.1.1.crate",
        sha256: "f77b8032dc584527975f34aa5a897d0ef5a785573fda778771a614ff9da501d9",
        file: "ripgrep-14.1.1.crate",
    },
    PinDef {
        key: "rust-source",
        aliases: &[],
        // The upstream source release is comprehensive: vendored Cargo sources,
        // in-tree Cargo, and llvm-project are all inside this fixed-output input.
        url: "https://static.rust-lang.org/dist/rustc-1.96.0-src.tar.xz",
        sha256: "b99ce16cdf0ecfc761b585ac84d131b46733465a02f8ecd0ff2de9713c62ee09",
        file: "rustc-1.96.0-src.tar.xz",
    },
    PinDef {
        key: "rust-stage0-rustc-source",
        aliases: &[],
        // Exact bootstrap compiler selected by rustc 1.96.0's src/stage0.
        url: "https://static.rust-lang.org/dist/2026-04-16/rustc-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
        sha256: "8426a3d170a5879f5682f5fbdd024a1779b3951e7baba685af2d6dc32a6dfc15",
        file: "rustc-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
    },
    PinDef {
        key: "rust-stage0-std-source",
        aliases: &[],
        url: "https://static.rust-lang.org/dist/2026-04-16/rust-std-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
        sha256: "047ea7098803d3500fa1072e9cee5392697e21525559e4458128a2bf874aa382",
        file: "rust-std-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
    },
    PinDef {
        key: "rust-stage0-cargo-source",
        aliases: &[],
        url: "https://static.rust-lang.org/dist/2026-04-16/cargo-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
        sha256: "e74edd2cf7d0f1f1383b4f00eb90c843750bc489e2ccf7214e6476678a907425",
        file: "cargo-1.95.0-x86_64-unknown-linux-gnu.tar.xz",
    },
    PinDef {
        key: "sed-mesboot-source",
        aliases: &[],
        // GNU sed 4.2.2 — the from-source `sed` provider (re #469), a sibling of
        // the gawk-mesboot rung: gcc-mesboot1 + glibc-mesboot0 build it exactly as
        // gawk 3.1.8 is built one tier down. Its gnulib papers over glibc 2.2.5
        // gaps the same way gawk's does, so no host `sed` need leak onto a rung
        // that can reach this output.
        url: "https://ftp.gnu.org/gnu/sed/sed-4.2.2.tar.gz",
        sha256: "fea0a94d4b605894f3e2d5572e3f96e4413bcad3a085aae7367c2cf07908b2ff",
        file: "sed-4.2.2.tar.gz",
    },
    PinDef {
        key: "sed-mesboot0-source",
        aliases: &[],
        // GNU sed 4.0.9 — the tcc-era `sed` provider (re #469). The exact
        // version live-bootstrap builds under tcc + mes libc (its LIBC=mes mk
        // branch), a cycle-breaker below the first host-tool consumer. NOT the
        // heavier sed 4.2.2 the gcc-mesboot1-era `sed-mesboot` rung uses.
        url: "https://ftp.gnu.org/gnu/sed/sed-4.0.9.tar.gz",
        sha256: "c365874794187f8444e5d22998cd5888ffa47f36def4b77517a808dec27c0600",
        file: "sed-4.0.9.tar.gz",
    },
    PinDef {
        key: "stage0-source",
        aliases: &[],
        url: "https://github.com/oriansj/stage0-posix/releases/download/Release_1.9.1/stage0-posix-1.9.1.tar.gz",
        sha256: "f4fdda675de90ab034fd3467ef43cddff61b3d372f8e0e5c2d25d145f224226f",
        file: "stage0-posix-1.9.1.tar.gz",
    },
    PinDef {
        key: "tcc-source",
        aliases: &[],
        url: "https://lilypond.org/janneke/tcc/tcc-0.9.26-1149-g46a75d0c.tar.gz",
        sha256: "f4f6ce121ac631a234af080753fb9d645d2334d20160b37abbe75b574a1e1d19",
        file: "tcc-0.9.26-1149-g46a75d0c.tar.gz",
    },
    PinDef {
        key: "tcc-0.9.27-source",
        aliases: &[],
        url: "https://download.savannah.nongnu.org/releases/tinycc/tcc-0.9.27.tar.bz2",
        sha256: "de23af78fca90ce32dff2dd45b3432b2334740bb9bb7b05bf60fdbfc396ceb9c",
        file: "tcc-0.9.27.tar.bz2",
    },
    PinDef {
        key: "util-linux-libs-x86-64-source",
        aliases: &[],
        // btrfs-progs requires libuuid and libblkid. The recipe builds only
        // those two static libraries; no util-linux programs are shipped.
        url: "https://www.kernel.org/pub/linux/utils/util-linux/v2.42/util-linux-2.42.2.tar.xz",
        sha256: "03a05d3adf9602ef128f2da05b84b3205ce60c351e5737c0370f74000679ce8a",
        file: "util-linux-2.42.2.tar.xz",
    },
    PinDef {
        key: "uutils-source",
        aliases: &[],
        // uutils coreutils 0.9.0 — the read-only-root Rust core userland (#547).
        // The `--auto` source_input pin; the dependency closure is pinned
        // separately by the committed recipes/locks/uutils/Cargo.lock.
        url: "https://static.crates.io/crates/coreutils/coreutils-0.9.0.crate",
        sha256: "b92df9b821533650f3797aadae46e547f72db281c1f8a27f381f36d54284d34b",
        file: "coreutils-0.9.0.crate",
    },
    PinDef {
        key: "zlib-x86-64-source",
        aliases: &[],
        url: "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz",
        sha256: "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23",
        file: "zlib-1.3.1.tar.gz",
    },
];

/// The pins APPLICATIONS.md §B.8 marks FOREIGN: a prebuilt payload that is not a
/// bootstrap seed and never becomes one.
///
/// A roster rather than a field on every `PinDef`, for UNSAFE.md's reason — the
/// COUNT is what a reviewer reads, and `foreign: false` written fifty-odd times
/// buries the one entry that matters. The hole a name-keyed roster would
/// otherwise have is the one this workstream has already refused twice, a
/// declaration that reaches nothing reading as enforcement: `every_foreign_name_
/// is_a_pin_key` closes it, and requires a KEY rather than an alias, since
/// marking an alias would leave the canonical key unmarked.
///
/// Adding an entry is a reviewed pin; adding a CLASS of foreign output is an
/// AGENTS.md amendment.
const FOREIGN: &[&str] = &["ripgrep-seed-source"];

pub fn all() -> Vec<SourcePin> {
    all_with(FOREIGN)
}

pub fn by_key(key: &str) -> Option<SourcePin> {
    by_key_with(key, FOREIGN)
}

/// Every NAME a §B.8-marked pin answers to — its key AND its aliases.
///
/// A set built from keys alone is a hole rather than an approximation, and
/// review is what found it: `by_key` RESOLVES an alias, so a recipe naming a
/// marked pin by one gets the payload's bytes with the mark intact, while a
/// key-only set answers "not marked" for that same name. The tool-channel
/// refusal and the closure query both ask that set, so the pin would be neither
/// refused nor reported. Two shipped pin names are aliases today, so this is
/// reachable rather than hypothetical.
pub fn foreign_names() -> Vec<String> {
    foreign_names_with(FOREIGN)
}

fn all_with(foreign: &[&str]) -> Vec<SourcePin> {
    PINS.iter()
        .map(|pin| materialize_with(pin, pin.key, foreign))
        .collect()
}

fn foreign_names_with(foreign: &[&str]) -> Vec<String> {
    PINS.iter()
        .filter(|pin| foreign.contains(&pin.key))
        .flat_map(|pin| std::iter::once(pin.key).chain(pin.aliases.iter().copied()))
        .map(str::to_string)
        .collect()
}

fn by_key_with(key: &str, foreign: &[&str]) -> Option<SourcePin> {
    PINS.iter()
        .find(|pin| pin.key == key || pin.aliases.iter().any(|alias| *alias == key))
        .map(|pin| materialize_with(pin, key, foreign))
}

/// Every function above takes its roster as an ARGUMENT, and the public entry
/// points exist only to supply `FOREIGN`. The behavior remains tested through the
/// `_with` pair over fixtures so misspellings, aliases and an empty roster stay
/// observable independently of the reviewed production entry. The wiring is
/// pinned in source by
/// `the_public_pair_is_the_only_place_the_real_roster_is_read`.
fn materialize_with(pin: &PinDef, key: &str, foreign: &[&str]) -> SourcePin {
    let out = SourcePin::new(key, pin.url, pin.sha256, pin.file);
    // Keyed on the PIN's own key, never on `key` — which may be an ALIAS, and a
    // pin that is foreign under one name and ordinary under another is the same
    // bytes admitted twice under two different trust answers.
    if foreign.contains(&pin.key) {
        out.mark_foreign()
    } else {
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_carries_all_legacy_source_locks() {
        // 32 migrated legacy locks + oyacc-6.6 (the from-source `yacc`) +
        // bash-2.05b (the from-source bootstrap shell it regenerates, re #469) +
        // sed-4.2.2 (the gcc-mesboot1-era `sed` provider, re #469) +
        // sed-4.0.9 (the tcc-era `sed` cycle-breaker, re #469) +
        // coreutils-5.0 (the tcc-era coreutils cycle-breaker, re #469) +
        // grep-2.4 (the tcc-era `grep` cycle-breaker, re #469) +
        // gawk-3.0.4 (the tcc-era `gawk` cycle-breaker, re #469) +
        // diffutils-2.7 (the tcc-era `diffutils` cycle-breaker, re #469) +
        // m4-1.4.19 (the glibc-rung `bison` provider's macro processor, re #469) +
        // bison-3.8.2 (the glibc-rung parser generator, re #469) +
        // Python-3.11.1 (the glibc-rung python3, re #469) + GCC 10.5.0 (the
        // compatibility bridge between gcc-mesboot 4.9.4 and GCC 14.3.0) +
        // the linux-x86-64 kernel source (separate from the 4.14 UAPI-header
        // pin, re #529) + flex-2.6.4 and elfutils-0.192 (the modern-kernel host
        // tools flex + libelf, re #529) + CMake 3.31.12 + Rust 1.96.0 source and
        // its exact three-component Rust 1.95.0 bootstrap snapshot +
        // coreutils-0.9.0, ripgrep 14.1.1, and fd 10.2.0 (the Rust userland
        // `.crate` sources) +
        // btrfs-progs 7.0 and util-linux 2.42.2 (the persistent-volume writer
        // and its minimal libuuid/libblkid build closure) + the first reviewed
        // foreign application seed, upstream ripgrep 15.2.0, LibreSSL 4.3.2,
        // curl 8.21.0 (the static HTTPS foundation for Git), Git 2.55.0, and
        // curl's dated Mozilla CA extract, OpenAI Codex 0.148.0 (including its
        // vendored Bubblewrap and five Cargo Git commit archives), libcap 2.78,
        // and Protobuf 31.1 with its exact Abseil 20250127.0 source dependency.
        assert_eq!(all().len(), 70);
    }

    /// A roster keyed by NAME can name nothing, and this workstream has twice
    /// refused that shape: a declaration reaching no path reads as enforcement
    /// and is none. Here it would be worse than a no-op — a misspelt entry
    /// leaves the payload it meant to mark UNMARKED, which is the answer every
    /// check downstream then gives.
    ///
    /// A KEY and never an alias, because `materialize` marks on `pin.key`: an
    /// alias listed here would resolve to a pin that is foreign under one name
    /// and ordinary under another.
    fn unresolved(foreign: &[&str], pins: &[PinDef]) -> Vec<String> {
        foreign
            .iter()
            .filter(|name| !pins.iter().any(|pin| pin.key == **name))
            .map(|name| (*name).to_string())
            .collect()
    }

    #[test]
    fn every_foreign_name_is_a_pin_key() {
        // This fixture keeps the misspelling and alias cases observable without
        // depending on whichever reviewed pins the real roster currently names.
        let pins = [PinDef {
            key: "app",
            aliases: &["app-alias"],
            url: "u",
            sha256: "s",
            file: "f",
        }];
        assert!(unresolved(&["app"], &pins).is_empty());
        assert_eq!(unresolved(&["typo"], &pins), vec!["typo".to_string()]);
        assert_eq!(
            unresolved(&["app-alias"], &pins),
            vec!["app-alias".to_string()],
            "an alias must not satisfy the check — materialize marks on the key"
        );
        assert!(
            unresolved(FOREIGN, PINS).is_empty(),
            "a FOREIGN name that resolves to no pin marks nothing, and every \
             check downstream then answers `not foreign'"
        );
        // The count is the reviewable artifact, so it is asserted rather than
        // left to be read. Adding an application changes this number.
        assert_eq!(FOREIGN.len(), 1, "exactly one application seed is admitted");
    }

    /// The mark is a property of the PIN, so it must answer the same however the
    /// pin was asked for — and an ALIAS in the roster must mark nothing, which is
    /// what makes the key-only rule above load-bearing rather than a convention.
    #[test]
    fn the_mark_rides_the_pin_not_the_name_it_was_asked_for() {
        let pin = PinDef {
            key: "app",
            aliases: &["app-alias"],
            url: "u",
            sha256: "s",
            file: "f",
        };
        assert!(materialize_with(&pin, "app", &["app"]).foreign());
        assert!(
            materialize_with(&pin, "app-alias", &["app"]).foreign(),
            "asking by alias must not lose the mark"
        );
        assert!(!materialize_with(&pin, "app", &["other"]).foreign());
        assert!(
            !materialize_with(&pin, "app", &["app-alias"]).foreign(),
            "an alias in the roster marks nothing — hence the key-only check"
        );
        let marked: Vec<String> = all()
            .into_iter()
            .filter(|pin| pin.foreign())
            .map(|pin| pin.key)
            .collect();
        assert_eq!(marked, vec!["ripgrep-seed-source".to_string()]);
    }

    /// The PRODUCTION lookup, over a REAL pin key, which is the route every
    /// shipped recipe takes: no catalog recipe calls `source_pin` directly, so
    /// the fixture-`PinDef` test above and the shipped code met nowhere until
    /// this one. Driven through `by_key_with` so the fixture can mark an ordinary
    /// production pin without changing the reviewed roster.
    #[test]
    fn the_production_lookup_marks_a_real_pin_from_the_roster() {
        let key = "zlib-x86-64-source";
        assert!(!by_key(key).unwrap().foreign(), "ordinary as shipped");
        assert!(by_key_with(key, &[key]).unwrap().foreign());
        assert_eq!(
            all_with(&[key])
                .iter()
                .filter(|pin| pin.foreign())
                .map(|pin| pin.key.clone())
                .collect::<Vec<_>>(),
            vec![key.to_string()],
            "exactly the named pin, and no neighbour"
        );
    }

    /// Pin the one production read of the reviewed roster. Value tests prove
    /// the current seed is marked; this source assertion also refuses a second
    /// bypassing materializer or an alternate roster read.
    #[test]
    fn the_public_pair_is_the_only_place_the_real_roster_is_read() {
        let src = include_str!("source_pins.rs");
        let shipped = match src.find("\n#[cfg(test)]\nmod tests {") {
            Some(at) => src.get(..at).unwrap_or(src),
            None => src,
        };
        let reads: Vec<&str> = shipped
            .lines()
            .map(str::trim)
            .filter(|l| l.contains("FOREIGN") && !l.starts_with("///") && !l.starts_with("//"))
            .collect();
        assert_eq!(
            reads,
            vec![
                "const FOREIGN: &[&str] = &[\"ripgrep-seed-source\"];",
                "all_with(FOREIGN)",
                "by_key_with(key, FOREIGN)",
                "foreign_names_with(FOREIGN)",
            ],
            "the roster is declared once and read by exactly the three public \
             entry points — a fourth reader, or any of these passing something \
             else, is how a marked pin comes back unmarked"
        );
    }

    /// A marked pin answers to its ALIASES too, which is what `by_key` does and
    /// what a key-only set silently disagreed with. Driven over the real
    /// `linux-source` pin, whose two aliases are the reachable case.
    #[test]
    fn a_marked_pins_aliases_are_marked_with_it() {
        const KEY: &str = "linux-source";
        let mut names = foreign_names_with(&[KEY]);
        names.sort();
        assert_eq!(
            names,
            vec![
                "linux-headers".to_string(),
                "linux-headers-x86-64".to_string(),
                KEY.to_string(),
            ],
            "every name `by_key' resolves to a marked pin must be marked"
        );
        // A pin with no alias contributes exactly its key, and a neighbour's
        // names are not swept in with it.
        assert_eq!(
            foreign_names_with(&["zlib-x86-64-source"]),
            vec!["zlib-x86-64-source".to_string()]
        );
        assert!(foreign_names_with(&[]).is_empty());
        // A name that resolves to no pin contributes nothing, which is what
        // `every_foreign_name_is_a_pin_key` refuses at the roster instead.
        assert!(foreign_names_with(&["linux-headers"]).is_empty());
    }

    #[test]
    fn linux_header_inputs_resolve_to_the_linux_source_pin() {
        let linux = by_key("linux-headers-x86-64").unwrap();
        assert_eq!(linux.file, "linux-4.14.67.tar.xz");
        assert_eq!(linux.key, "linux-headers-x86-64");
    }
}
