[package]
name = "td-busd"
version = "0.1.0"
edition = "2021"
description = "td's session D-Bus broker"
license = "GPL-3.0-or-later"

[workspace]

[[bin]]
name = "td-busd"
path = "src/main.rs"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
unreachable = "deny"
todo = "deny"
unimplemented = "deny"
indexing_slicing = "deny"

[profile.release]
opt-level = "s"
panic = "abort"
strip = true
