//! Flat service ownership and response adapters around td-mime.
#[path = "mime_response/body_json.rs"]
pub mod body_json;
#[path = "mime_response/body_window.rs"]
pub mod body_window;
#[path = "mime_response/bound.rs"]
pub mod bound;
#[path = "mime_response/framing.rs"]
pub(crate) mod framing;
#[path = "mime_response/lists.rs"]
pub mod lists;
#[path = "mime_response/locators.rs"]
pub mod locators;
#[path = "mime_response/metadata.rs"]
pub mod metadata;
#[path = "mime_response/metadata_collection.rs"]
pub mod metadata_collection;
#[path = "mime_response/metadata_json.rs"]
pub mod metadata_json;
#[path = "mime_response/metadata_json_window.rs"]
pub mod metadata_json_window;
#[path = "mime_response/metadata_window.rs"]
pub mod metadata_window;
#[path = "mime_response/ordered.rs"]
pub mod ordered;
#[path = "mime_response/part_collection.rs"]
pub mod part_collection;
#[path = "mime_response/part_json.rs"]
pub mod part_json;
#[path = "mime_response/part_window.rs"]
pub mod part_window;
#[path = "mime_response/pinned.rs"]
pub mod pinned;
#[path = "mime_response/requested_body_json.rs"]
pub mod requested_body_json;
#[path = "mime_response/requested_body_window.rs"]
pub mod requested_body_window;
#[path = "mime_response/requested_selected_json.rs"]
pub mod requested_selected_json;
#[path = "mime_response/requested_selected_window.rs"]
pub mod requested_selected_window;
#[path = "mime_response/response.rs"]
pub mod response;
#[path = "mime_response/selected_body_json.rs"]
pub mod selected_body_json;
#[path = "mime_response/selected_body_window.rs"]
pub mod selected_body_window;
#[path = "mime_response/selected_metadata.rs"]
pub mod selected_metadata;
#[path = "mime_response/selected_metadata_collection.rs"]
pub mod selected_metadata_collection;
#[path = "mime_response/selected_metadata_json.rs"]
pub mod selected_metadata_json;
#[path = "mime_response/selected_metadata_window.rs"]
pub mod selected_metadata_window;
#[path = "mime_response/selection_index.rs"]
mod selection_index;
#[path = "mime_response/subparts_json.rs"]
pub mod subparts_json;
#[path = "mime_response/subparts_window.rs"]
pub mod subparts_window;
