# td bash-2.05b Makefile (re #469) — live-bootstrap's mk/main.mk with td's
# tcc/mes/oyacc store paths baked in and the ~45 -D config macros moved into
# config.h (see bash-mesboot-common.mk). Driven by td's Make 3.80: every recipe
# line below is metacharacter-free, so make's no-shell fast path execs tcc/yacc
# directly (the sandbox has no $(SHELL)). This is load-bearing — a single `"`,
# `(`, `$`-glob, etc. on a recipe line makes make reach for a shell that does
# not exist. Keep the command word first and every argument metacharacter-free.
include common.mk

CFLAGS = -I. -Iinclude -Ilib -Ilib/sh -Ibuiltins $(COMMON_CFLAGS)

LDFLAGS = -L. -Lbuiltins -L{in:tcc}/lib -static
LIBRARIES = libsh.a builtins/libbuiltins.a libglob.a libtilde.a

SHLIB_FILES = clktck getcwd getenv oslib setlinebuf strcasecmp strerror strtod \
	vprint itos rename zread zwrite shtty inet_aton netopen \
	strpbrk timeval clock makepath pathcanon pathphys stringlist stringvec \
	tmpfile spell strtrans strindex shquote snprintf mailstat fmtulong \
	fmtullong strtoll strtoull strtoimax strtoumax fmtumax netconn mktime \
	strftime xstrchr zcatfd
# FIXME (upstream): these don't get picked up in the final link, so they are
# re-listed explicitly on the bash link line via SHLIB_ODD_OBJS.
SHLIB_ODD_FILES = zcatfd strtoumax spell pathphys
SHLIB_OBJS = $(addprefix lib/sh/, $(addsuffix .o, $(SHLIB_FILES)))
SHLIB_ODD_OBJS = $(addprefix lib/sh/, $(addsuffix .o, $(SHLIB_ODD_FILES)))

MKBUILTINS_OBJS = builtins/mkbuiltins.o
BUILTINS_DEFS = $(addprefix builtins/, $(addsuffix .def, $(BUILTINS_DEF_FILES)))

GLOB_FILES = glob strmatch smatch xmbsrtowcs
GLOB_OBJS = $(addprefix lib/glob/, $(addsuffix .o, $(GLOB_FILES)))

TILDE_OBJS = lib/tilde/tilde.o

MKSYNTAX_OBJS = mksyntax.o
MKSIGNAMES_OBJS = support/mksignames.o

FILES = shell eval y.tab general make_cmd print_cmd dispose_cmd execute_cmd \
	variables copy_cmd error expr flags nojobs subst hashcmd hashlib mailcheck \
	trap input unwind_prot pathexp sig test version alias array arrayfunc \
	braces bracecomp bashhist bashline list stringlib locale findcmd redir \
	pcomplete pcomplib syntax xmalloc siglist
OBJS = $(addsuffix .o, $(FILES))

all: bash

# Builtins generator (also runs it to emit builtext.h + builtins.c)
mkbuiltins: $(MKBUILTINS_OBJS)
	$(CC) $(CFLAGS) $(MKBUILTINS_OBJS) $(LDFLAGS) -o $@
	./mkbuiltins -externfile builtins/builtext.h -structfile builtins/builtins.c -noproduction $(BUILTINS_DEFS)

libsh.a: $(SHLIB_OBJS)
	$(AR) cr $@ $^

libglob.a: $(GLOB_OBJS)
	$(AR) cr $@ $^

libtilde.a: $(TILDE_OBJS)
	$(AR) cr $@ $^

mksyntax: $(MKSYNTAX_OBJS)
	$(CC) $^ $(LDFLAGS) -o $@ -lgetopt

syntax.c: mksyntax
	./mksyntax -o $@

mksignames: $(MKSIGNAMES_OBJS)
	$(CC) $^ $(LDFLAGS) -o $@ -lgetopt

signames.h: mksignames
	./mksignames $@

# The parser is regenerated by td's oyacc `yacc` (the recipe also pre-runs this
# before make, so the shipped bison output is never trusted; re #469).
y.tab.c: parse.y
	{in:oyacc}/bin/yacc -d $^

trap.c: signames.h

bash: libsh.a libglob.a libtilde.a $(OBJS)
	$(CC) -o bash $(LIBRARIES) $(OBJS) $(SHLIB_ODD_OBJS) $(LDFLAGS) -lsh -lbuiltins -lglob -ltilde
