use crate::ladder::unpack_into;
use crate::types::{Recipe, Step, TextEdit};

// GNU bash 2.05b — the from-source bootstrap shell (re #469). live-bootstrap
// builds this exact version under tcc + mes libc, its parser regenerated by the
// oyacc rung's `yacc`; td does the same, host-tool-free. Differences from
// live-bootstrap's steps/bash-2.05b (pass1.kaem), all forced by td's sandbox:
//
//   * No patch/sed: the 5 mes-libc/tcc patches are engine-native, count-checked
//     `SubstituteText` edits, each transcribed from the upstream hunk.
//   * No shell: td's Make 3.80 drives the build, but the sandbox has no $(SHELL),
//     so every baked-Makefile recipe line is metacharacter-free (make's no-shell
//     fast path execs tcc/yacc directly). live-bootstrap supplies bash's ~45
//     config macros as `-D` flags on the tcc command line; many carry `"`/`(`
//     (shell metacharacters), so td moves them ALL into config.h instead (bash
//     `#include`s it unconditionally) — see bash-mesboot-config.h.
//   * The parser is regenerated by td's oyacc, never the shipped bison y.tab.c.
//
// Inputs: mes (headers + libc + getopt.h), tcc (compiler + libgetopt.a),
// make-mesboot0 (`make`), oyacc (`yacc`) — no host tools. Installs as bash + sh.
const CONFIG_H: &str = include_str!("bash-mesboot-config.h");
const MAKEFILE: &str = include_str!("bash-mesboot.mk");
const BUILTINS_MK: &str = include_str!("bash-mesboot-builtins.mk");
const COMMON_MK: &str = include_str!("bash-mesboot-common.mk");

pub fn recipe() -> Recipe {
    let mut steps = unpack_into("bash-mesboot-source", "{src}");

    // Config + empty stub headers. live-bootstrap `touch`es config.h,
    // include/version.h, include/pipesize.h (all absent in the tarball) and
    // supplies config via -D; td bakes the 45 defines into config.h and keeps
    // version.h/pipesize.h empty (their values come from config.h).
    steps.push(Step::WriteFile {
        path: "{src}/config.h".into(),
        content: CONFIG_H.into(),
        exec: false,
    });
    steps.push(Step::WriteFile {
        path: "{src}/include/version.h".into(),
        content: String::new(),
        exec: false,
    });
    steps.push(Step::WriteFile {
        path: "{src}/include/pipesize.h".into(),
        content: String::new(),
        exec: false,
    });

    // td-adapted Makefiles (mk/main.mk -> Makefile, mk/builtins.mk ->
    // builtins/Makefile, mk/common.mk -> common.mk), tcc/mes/oyacc baked in.
    steps.push(Step::WriteFile {
        path: "{src}/Makefile".into(),
        content: MAKEFILE.into(),
        exec: false,
    });
    steps.push(Step::WriteFile {
        path: "{src}/builtins/Makefile".into(),
        content: BUILTINS_MK.into(),
        exec: false,
    });
    steps.push(Step::WriteFile {
        path: "{src}/common.mk".into(),
        content: COMMON_MK.into(),
        exec: false,
    });

    // The 5 patches live-bootstrap's pass1.kaem applies, as count-checked edits.

    // mes-libc.patch (lib/sh/snprintf.c): mes libc has no locale support.
    steps.push(Step::substitute_text(
        "{src}/lib/sh/snprintf.c",
        vec![TextEdit::new("#if defined (HAVE_LOCALE_H)", "#if 0", 1)],
    ));

    // tinycc.patch (lib/sh/oslib.c): tcc mishandles the split/`int name,namelen`
    // K&R parameter declarations for gethostname; collapse them to one line.
    steps.push(Step::substitute_text(
        "{src}/lib/sh/oslib.c",
        vec![
            TextEdit::new(
                "     char *name;\n     int namelen;",
                "     char *name; int namelen;",
                1,
            ),
            TextEdit::new(
                "     int name, namelen;",
                "     char* name; int namelen;",
                1,
            ),
        ],
    ));

    // missing-defines.patch (execute_cmd.c): gate the cm_cond/cm_arith/
    // cm_arith_for arms behind their feature macros. Only COND_COMMAND is
    // defined (config.h), so the arith arms compile out — their enum tags and
    // union members do not exist without DPAREN_ARITHMETIC/ARITH_FOR_COMMAND.
    steps.push(Step::substitute_text(
        "{src}/execute_cmd.c",
        vec![
            TextEdit::new(
                "      else if (currently_executing_command->type == cm_cond)\n\treturn currently_executing_command->value.Cond->line;",
                "#ifdef COND_COMMAND\n      else if (currently_executing_command->type == cm_cond)\n\treturn currently_executing_command->value.Cond->line;\n#endif",
                1,
            ),
            TextEdit::new(
                "      else if (currently_executing_command->type == cm_arith)\n\treturn currently_executing_command->value.Arith->line;",
                "#ifdef DPAREN_ARITHMETIC\n      else if (currently_executing_command->type == cm_arith)\n\treturn currently_executing_command->value.Arith->line;\n#endif",
                1,
            ),
            TextEdit::new(
                "      else if (currently_executing_command->type == cm_arith_for)\n\treturn currently_executing_command->value.ArithFor->line;",
                "#ifdef ARITH_FOR_COMMAND\n      else if (currently_executing_command->type == cm_arith_for)\n\treturn currently_executing_command->value.ArithFor->line;\n#endif",
                1,
            ),
        ],
    ));

    // locale.patch (locale.c): mes libc setlocale is unusable — stub set_lang.
    steps.push(Step::substitute_text(
        "{src}/locale.c",
        vec![TextEdit::new(
            "  return ((lc_all == 0 || *lc_all == 0) ? setlocale (LC_ALL, value?value:\"\") != NULL : 0);",
            "  return 0;",
            1,
        )],
    ));

    // dev-tty.patch (shell.c): there is no /dev/tty at this bootstrap stage, and
    // bash is not interactive here — drop the check (also its extern reference).
    steps.push(Step::substitute_text(
        "{src}/shell.c",
        vec![TextEdit::new("  check_dev_tty ();", "  ;", 1)],
    ));

    // Regenerate the parser with td's own oyacc `yacc` (re #469: never trust the
    // shipped bison y.tab.c). Overwrites y.tab.c / y.tab.h in {src}.
    steps.push(
        Step::run("{src}", &["{in:oyacc}/bin/yacc", "-d", "parse.y"])
            .env("LANG", "")
            .env("LC_ALL", ""),
    );

    // Build, mirroring pass1.kaem's three make invocations (LANG/LC_ALL cleared
    // for determinism; make finds tcc/yacc via baked absolute paths, no PATH).
    // 1. mkbuiltins (its recipe also RUNS mkbuiltins to emit builtext.h +
    //    builtins.c).
    steps.push(
        Step::run("{src}", &["{in:make-mesboot0}/bin/make", "mkbuiltins"])
            .env("LANG", "")
            .env("LC_ALL", ""),
    );
    // 2. libbuiltins.a in builtins/.
    steps.push(
        Step::run(
            "{src}/builtins",
            &["{in:make-mesboot0}/bin/make", "libbuiltins.a"],
        )
        .env("LANG", "")
        .env("LC_ALL", ""),
    );
    // 3. the shell itself (default target: bash).
    steps.push(
        Step::run("{src}", &["{in:make-mesboot0}/bin/make"])
            .env("LANG", "")
            .env("LC_ALL", ""),
    );

    // Install bash, and sh as a relative symlink to it (live-bootstrap installs
    // sh as a second copy; a symlink is equivalent and store-relocatable).
    steps.push(Step::MkDir {
        path: "{out}/bin".into(),
    });
    steps.push(Step::CopyFiles {
        files: vec!["{src}/bash".into()],
        dest: "{out}/bin".into(),
    });
    steps.push(Step::Symlink {
        target: "bash".into(),
        link: "{out}/bin/sh".into(),
    });
    steps.push(Step::Require {
        paths: vec!["{out}/bin/bash".into()],
        exec: true,
    });
    steps.push(Step::Require {
        paths: vec!["{out}/bin/sh".into()],
        exec: false,
    });

    // Runtime provenance (re #469): the link is -static, so bash must carry no
    // host loader (PT_INTERP) or host libc (DT_NEEDED); red the rung otherwise.
    steps.push(Step::assert_static(&["{out}/bin/bash"]));

    // Smoke: the installed shell must actually parse and execute — as bash (the
    // `test` builtin) and through the `sh` symlink.
    steps.push(Step::run("{src}", &["{out}/bin/bash", "-c", "test 1 = 1"]));
    steps.push(Step::run("{src}", &["{out}/bin/sh", "-c", "exit 0"]));

    Recipe::mesboot("bash-mesboot", "2.05b")
        .source_input("bash-mesboot-source")
        .native_inputs(&["mes", "tcc", "make-mesboot0", "oyacc"])
        .steps(steps)
}
