//! Generates the gate registry from `src/gate_defs/*.rs` — the same
//! self-registering one-file-per-entry pattern as the recipe catalog
//! (recipes/build.rs, issue #295), applied to the check gates when the gate
//! runner replaced make + the mk/gates/*.mk fragments.
//!
//! Each gate is one file: the FILE NAME (minus `.rs`) is the stem
//! `<NNN>-<gate-name>` — the `<NNN>` prefix keeps the registration/serial
//! order the fragments carried — and the file exports `pub fn gate() ->
//! GateDef`. This script globs the directory and writes
//! `$OUT_DIR/gate_registry.rs` (module declarations + the stem-sorted `all()`
//! table), which `src/gates.rs` includes. Adding a gate touches only its new
//! file: no shared source line, so concurrent gate PRs never collide — the
//! property the mk/gates/ drop-ins had, now compiler-checked.
//!
//! Deterministic by construction: sorted by stem, never `read_dir` order.
//! Pure `std` — the crate stays dependency-free.

use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed=src/gate_defs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let dir = PathBuf::from(&manifest_dir).join("src/gate_defs");
    let mut stems: Vec<String> = Vec::new();
    for entry in fs::read_dir(&dir)? {
        let entry = entry?;
        let name = entry.file_name();
        let name = name.to_str().ok_or("non-UTF-8 filename in src/gate_defs")?;
        if entry.file_type()?.is_dir() {
            return Err(format!(
                "src/gate_defs/{name} is a directory — the gate layout is FLAT, \
                 one <NNN>-<gate>.rs per gate directly in src/gate_defs/"
            )
            .into());
        }
        if name.starts_with('.') {
            continue; // editor droppings
        }
        let Some(stem) = name.strip_suffix(".rs") else {
            continue;
        };
        // `<NNN>-<gate-name>`: digits, then '-', then the gate-name charset.
        let ok = stem.len() > 4
            && stem.chars().take(3).all(|c| c.is_ascii_digit())
            && stem
                .chars()
                .skip(3)
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '_')
            && stem.chars().nth(3) == Some('-');
        if !ok {
            return Err(format!(
                "src/gate_defs/{name}: stem must be <NNN>-<gate-name> \
                 ([0-9]{{3}}-[a-z0-9_-]+ — the NNN prefix is the registration order)"
            )
            .into());
        }
        stems.push(stem.to_string());
    }
    stems.sort();
    if stems.is_empty() {
        return Err("src/gate_defs is empty — the gate ladder would be vacuous".into());
    }

    let mut out = String::new();
    writeln!(out, "// @generated by build.rs from src/gate_defs/*.rs — do not edit.")?;
    for stem in &stems {
        // A digit-led stem cannot be a module identifier — prefix `g`.
        let module = format!("g{}", stem.replace('-', "_"));
        let path = format!("{manifest_dir}/src/gate_defs/{stem}.rs");
        writeln!(out, "#[path = {path:?}]")?;
        writeln!(out, "pub mod {module};")?;
    }
    writeln!(out, "pub fn all() -> Vec<(&'static str, crate::gates::GateDef)> {{")?;
    writeln!(out, "    vec![")?;
    for stem in &stems {
        let module = format!("g{}", stem.replace('-', "_"));
        writeln!(out, "        ({stem:?}, {module}::gate()),")?;
    }
    writeln!(out, "    ]")?;
    writeln!(out, "}}")?;

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    fs::write(out_dir.join("gate_registry.rs"), out)?;
    Ok(())
}
