#!/bin/sh
# gen-feed-index.sh — regenerate tests/td-feed.index, the pinned td-feed mirror index:
# one `<path> <url> <sha256>` line per artifact this repo downloads over the network.
#
# This is a HOST/NETWORK-PREP generator (not a loop gate): it reads the REALIZED store
# paths the lock files already pin (so every crate's bytes are the daemon-verified FOD
# content) and emits, for each:
#   - sha256 = the flat content hash (`sha256sum` of the realized file) — the SAME hash
#     the feed verifies on warm + on serve, and (for crates) == the Cargo.lock checksum;
#   - name   = the crate's own [package] name (read from its embedded Cargo.toml), so the
#     static.crates.io URL `/crates/<name>/<name>-<version>.crate` is unambiguous even for
#     hyphenated / build-metadata names (md-5, toml_parser-1.1.2+spec-1.1.0);
#   - path   = the upstream `<host>/<path>` (the URL minus its scheme), so the feed is a
#     drop-in URL-path mirror and different hosts never collide.
#
# Sources: every `*.crate` across tests/*.lock (static.crates.io), explicit-URL test
# locks, and the recipe-owned source pins. Regenerate on a lock/source-pin bump; the
# committed index is pinned like a lock. The `feed-index` gate checks the result is
# self-consistent and that each crate's recorded sha256 == its realized content.
set -eu
root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/td-feed.index"
tmp=$(mktemp "${TMPDIR:-/tmp}/td-feed-index.XXXXXX")
trap 'rm -f "$tmp"' EXIT

emit() { # path url sha256
  printf '%s %s %s\n' "$1" "$2" "$3" >> "$tmp"
}

# --- crates: every distinct realized *.crate store path across the locks ---------------
crates=$(grep -rhoE '/gnu/store/[a-z0-9]+-[^ ]+\.crate' "$root"/tests/*.lock | sort -u)
ncrate=0; nmiss=0
for p in $crates; do
  test -e "$p" || { echo "gen-feed-index: NOT realized (warm the locks first): $p" >&2; nmiss=$((nmiss+1)); continue; }
  base=$(basename "$p")                       # <hash>-<name>-<version>.crate
  nv=$(printf '%s' "$base" | sed -E 's/^[a-z0-9]+-//; s/\.crate$//')   # <name>-<version>
  name=$(tar xOf "$p" "$nv/Cargo.toml" 2>/dev/null | awk '
    /^\[package\]/{inp=1;next} /^\[/{inp=0}
    inp&&/^name *=/{gsub(/.*= *"|".*/,"");print;exit}')
  test -n "$name" || { echo "gen-feed-index: no [package].name in $p ($nv)" >&2; exit 1; }
  sha=$(sha256sum "$p" | cut -d' ' -f1)
  emit "static.crates.io/crates/$name/$nv.crate" \
       "https://static.crates.io/crates/$name/$nv.crate" "$sha"
  ncrate=$((ncrate+1))
done
test "$nmiss" -eq 0 || { echo "gen-feed-index: $nmiss crate(s) not realized — run the warm prep" >&2; exit 1; }

# --- explicit-URL blobs: locks/source pins that carry `url` + `sha256` -------------------
# These are the td-NATIVE fetch artifacts (test locks plus recipe-owned source pins) —
# what td-fetch / tools/warm-*.sh request and what the SHARED feed actually warms+serves
# (the crates above stay catalog-only, daemon-served).
nblob=0
for lock in "$root"/tests/*.lock; do
  test -e "$lock" || continue
  url=$(sed -n 's/^url //p' "$lock" | head -1)
  sha=$(sed -n 's/^sha256 //p' "$lock" | head -1)
  test -n "$url" -a -n "$sha" || continue
  path=$(printf '%s' "$url" | sed -E 's,^https?://,,')
  emit "$path" "$url" "$sha"
  nblob=$((nblob+1))
done
eval_bin=${TD_RECIPE_EVAL:-}
if test -z "$eval_bin"; then
  eval_bin=`sh "$root/tests/recipe-eval-tool.sh" "$root/.td-build-cache/recipe-eval"` \
    || { echo "gen-feed-index: could not build td-recipe-eval from the current worktree" >&2; exit 1; }
fi
test -x "$eval_bin" || { echo "gen-feed-index: td-recipe-eval is not executable: $eval_bin" >&2; exit 1; }
while read -r key url sha file; do
  test -n "$key" -a -n "$url" -a -n "$sha" -a -n "$file" || continue
  path=$(printf '%s' "$url" | sed -E 's,^https?://,,')
  emit "$path" "$url" "$sha"
  nblob=$((nblob+1))
done <<EOF
`"$eval_bin" source-pins`
EOF

# --- write the pinned index (sorted, deduped) ------------------------------------------
{
  echo "# td-feed.index — pinned mirror index of every network-downloaded artifact in the"
  echo "# repo. One artifact per line: <path> <url> <sha256>. GENERATED by"
  echo "# tools/gen-feed-index.sh from the realized store paths the locks pin (HOST PREP);"
  echo "# the feed verifies each <sha256> on warm AND on serve. Regenerate on a lock or source-pin bump."
  echo "# $ncrate crates (static.crates.io) + $nblob source blob(s)."
  sort -u "$tmp"
} > "$out"
echo "gen-feed-index: wrote $out — $ncrate crates + $nblob source blob(s) = $(grep -cv '^#' "$out") lines"
