#!/usr/bin/env bash
# Generate PLAN.md's track table from the per-track status records in
# plan/tracks/*.md (one record = one track; `key: value` lines). The SINGLE
# source of truth for a track's status is its own record file, so a merged track
# flips to [x] by editing ITS file — there is no shared PLAN.md line to collide
# on (the gates-split win, applied to PLAN.md), and the `plan-index` gate fails
# the loop if PLAN.md drifts from the records (so a merged track cannot keep
# reading "claimed").
#
#   tools/plan-index.sh           rewrite PLAN.md's table from the records
#   tools/plan-index.sh --check   fail (non-zero) if PLAN.md is out of sync
#
# Pure bash + sed + sort: no awk (absent from the loop sandbox toolchain).
set -euo pipefail
cd "$(dirname "$0")/.."

BEGIN='<!-- BEGIN GENERATED TRACKS -->'
END='<!-- END GENERATED TRACKS -->'
TAB=$(printf '\t')

emit_section() { # $1 = section to emit (mainline|side)
  local want=$1 f
  for f in plan/tracks/*.md; do
    [ -e "$f" ] || continue
    local section='' status='' title='' handle='' date='' pr='' notes='' summary=''
    while IFS= read -r line || [ -n "$line" ]; do
      case "$line" in
        section:*) section=${line#section:} ;;
        status:*)  status=${line#status:} ;;
        title:*)   title=${line#title:} ;;
        handle:*)  handle=${line#handle:} ;;
        date:*)    date=${line#date:} ;;
        pr:*)      pr=${line#pr:} ;;
        notes:*)   notes=${line#notes:} ;;
        summary:*) summary=${line#summary:} ;;
      esac
    done < "$f"
    section=${section# }; status=${status# }; title=${title# }; handle=${handle# }
    date=${date# }; pr=${pr# }; notes=${notes# }; summary=${summary# }
    [ "$section" = "$want" ] || continue
    [ -n "$title" ] || { echo "plan-index: $f: missing title" >&2; exit 1; }

    local notestr=''
    case "$notes" in
      '')   notestr='' ;;
      '('*) notestr=" — $notes" ;;
      *)    notestr=" — \`$notes\`" ;;
    esac
    local prstr=''; [ -n "$pr" ] && prstr=", PR #$pr"
    local out
    case "$status" in
      done)    out="- [x] **$title** — DONE $date ($handle$prstr) — $summary$notestr" ;;
      closed)  out="- [x] **$title** — CLOSED $date ($handle$prstr) — $summary$notestr" ;;
      claimed) out="- [ ] **$title** — claimed $handle $date — $summary$notestr" ;;
      blocked) out="- [ ] **$title** — BLOCKED $date ($handle$prstr) — $summary$notestr" ;;
      *) echo "plan-index: $f: unknown status '$status' (want done|closed|claimed|blocked)" >&2; exit 1 ;;
    esac
    # Stable order: by date then title (deterministic across machines).
    printf '%s%s%s\n' "$date|$title" "$TAB" "$out"
  done | LC_ALL=C sort | sed "s/^[^$TAB]*$TAB//"
}

render_block() {
  printf '%s\n' "$BEGIN"
  printf '<!-- Generated by tools/plan-index.sh from plan/tracks/*.md — do NOT edit by hand. -->\n'
  printf '\n## Mainline (serial — one agent drives it at a time)\n\n'
  emit_section mainline
  printf '\n## Side-tracks (parallel-safe)\n\n'
  emit_section side
  printf '%s\n' "$END"
}

build() {
  grep -q -F "$BEGIN" PLAN.md && grep -q -F "$END" PLAN.md \
    || { echo "plan-index: PLAN.md is missing the BEGIN/END GENERATED TRACKS markers" >&2; exit 1; }
  sed "/$BEGIN/,\$d" PLAN.md   # everything before the BEGIN marker
  render_block
  sed "1,/$END/d" PLAN.md      # everything after the END marker
}

if [ "${1:-}" = "--check" ]; then
  if [ "$(build)" != "$(cat PLAN.md)" ]; then
    echo "plan-index: PLAN.md is OUT OF SYNC with plan/tracks/*.md." >&2
    echo "  A track's status changed but PLAN.md was not regenerated." >&2
    echo "  Fix: tools/plan-index.sh   (regenerates the table between the markers)" >&2
    exit 1
  fi
  echo "plan-index: PLAN.md matches plan/tracks/*.md"
else
  build > PLAN.md.tmp && mv PLAN.md.tmp PLAN.md
  echo "plan-index: PLAN.md regenerated from plan/tracks/*.md"
fi
