//! Ed25519 signature VERIFICATION (RFC 8032), pure `std` — the authenticity
//! half of a td deployment, and the one thing hashes cannot give it.
//!
//! Verify only, and that is the point rather than a limitation. Nothing here
//! generates a key, derives a public key, or produces a signature, so no
//! secret ever reaches this code and there is no constant-time obligation to
//! meet: every input is public (a pinned public key, a signature and a
//! manifest that ship together in the clear), and the code branches on them
//! freely. SIGNING stays host-side in `td-net`, where `ring` already does it
//! for narinfos, and a signing key never enters the target at all.
//!
//! Dependency-free for the reason the rest of the engine is: its INTENDED
//! consumer is `td-boot`, which runs in the boot shim before any store exists,
//! and no shipped td crate outside the network tools carries an external
//! crate. Nothing includes it yet — the `#[path]` include lands with the
//! verifying boot shim — and when it does it must declare BOTH this module and
//! `sha512` at its crate root, since `crate::sha512` is how this one reaches
//! the hash and that spelling resolves identically inside the engine lib and
//! inside an including binary. `net`'s test build already does exactly that.
//!
//! Correctness is pinned three ways, because a verifier that is merely
//! SLIGHTLY wrong still accepts every genuine signature and so is discovered
//! by nobody. Every constant below is RE-DERIVED in the tests from the
//! definition its name states — d from -121665/121666, 2d from d, sqrt(-1) by
//! squaring it, 2p by reducing it to zero — so a mistyped limb reds rather
//! than sitting there being almost right. The group law is checked against its
//! own algebra (the base point's order is L, `add(P,P) == double(P)`,
//! associativity). And `net/src/ed25519_cross.rs` signs with `ring` and
//! verifies HERE on fresh keys every run, holding the two implementations
//! against each other rather than against one recorded vector; the signatures
//! that check-in produced are the fixtures at the bottom of this file, so this
//! crate stays testable with no dependency present.
//!
//! Verification is STRICT — at least as strict as `ed25519-dalek`'s
//! `verify_strict`, and deliberately stronger about torsion. Every one of
//! these is a rejection:
//!
//!   - `S >= L` (the malleability case: `S + L` verifies under a verifier that
//!     omits this and is a SECOND valid signature for one message);
//!   - a non-canonical public key encoding (`y >= p`);
//!   - a public key OUTSIDE the prime-order subgroup, or the identity.
//!     That is the whole torsion class rather than a sample of it, and it is
//!     strictly stronger than `verify_strict`, which refuses a small-order key
//!     but admits a MIXED-order one. It has to be: `A = B + T` for a torsion
//!     point `T` is not small order, and any message whose hash comes out even
//!     then has a forgery with `R` at the identity — `a_mixed_order_key_is_refused`
//!     builds one and asserts it satisfies the verification equation before
//!     asserting it is refused, so the check cannot pass for the wrong reason.
//!     No honest key can fail this, since a public key is `[a]B`;
//!   - a small-order `R` — defence in depth once the key is torsion-free, but
//!     `R` is attacker-supplied where the key is pinned;
//!   - a non-canonical `R`, twice over: it fails to decompress, and could
//!     never equal the canonical re-encoding the equation compares against.
//!
//! The equation is still checked by comparing ENCODINGS — the expected point
//! is re-encoded and its 32 bytes compared to `R` — rather than by
//! decompressing `R` and comparing points. `R` is decompressed only to ask
//! whether it is small order.
//!
//! td signs and verifies with the same tools, so nothing legitimate is near
//! those edges; a strict verifier costs nothing and refuses the whole class.

use crate::sha512;

// ---- constants (generated by exact integer arithmetic, not transcribed) ----

/// d = -121665/121666, the Edwards parameter. Non-square in GF(p), which is
/// what makes the addition law below COMPLETE — no exceptional-case handling
/// for the identity, for doubling, or for adding a point to its own negative.
const D: Fe = Fe([
    0x34dca135978a3,
    0x1a8283b156ebd,
    0x5e7a26001c029,
    0x739c663a03cbb,
    0x52036cee2b6ff,
]);

/// 2d, the addition law's coefficient.
const D2: Fe = Fe([
    0x69b9426b2f159,
    0x35050762add7a,
    0x3cf44c0038052,
    0x6738cc7407977,
    0x2406d9dc56dff,
]);

/// sqrt(-1) = 2^((p-1)/4). p is 5 mod 8, so the square-root exponent below
/// yields a root of ±u and this is the fixup for the wrong one.
const SQRT_M1: Fe = Fe([
    0x61b274a0ea0b0,
    0x0d5a5fc8f189d,
    0x7ef5e9cbd0c60,
    0x78595a6804c9e,
    0x2b8324804fc1d,
]);

/// p-2: the inversion exponent (Fermat's little theorem).
const P_MINUS_2: [u8; 32] = [
    0xeb, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x7f,
];

/// (p-5)/8: the square-root exponent for p = 5 (mod 8).
const P_MINUS_5_DIV_8: [u8; 32] = [
    0xfd, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x0f,
];

/// L = 2^252 + 27742317777372353535851937790883648493, the prime order of the
/// base point's subgroup, as 64-bit words least-significant first.
const L: [u64; 4] = [
    0x5812_631a_5cf5_d3ed,
    0x14de_f9de_a2f7_9cd6,
    0x0000_0000_0000_0000,
    0x1000_0000_0000_0000,
];

/// The base point B, in its own 32-byte compressed encoding rather than as
/// hand-entered coordinates: it is decompressed through the same path a public
/// key takes, so the encoder/decoder pair is exercised on a point whose
/// coordinates are known before it is ever asked about one that is not.
const BASE_POINT: [u8; 32] = [
    0x58, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
    0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
];

/// 51 bits: the limb width. Five of them hold a field element.
const MASK: u64 = (1 << 51) - 1;
const MASK128: u128 = (1 << 51) - 1;

/// 2p, limb by limb — what `sub` adds before subtracting so no limb borrows.
/// Each is twice the corresponding limb of p = 2^255 - 19.
const TWO_P: [u64; 5] = [
    0xfffffffffffda,
    0xffffffffffffe,
    0xffffffffffffe,
    0xffffffffffffe,
    0xffffffffffffe,
];

pub const PUBLIC_KEY_LEN: usize = 32;
pub const SIGNATURE_LEN: usize = 64;

// ---- GF(2^255 - 19) ----

/// A field element as five 51-bit limbs, least significant first.
///
/// Every operation carry-propagates before returning, so a limb is always at
/// most 2^51 and the representation is WEAKLY reduced (a value may still
/// exceed p; only `to_bytes` reduces canonically). Reducing eagerly costs a
/// few adds and buys the property that makes this auditable: no operation has
/// a precondition about how reduced its inputs are, so no sequence of them can
/// overflow.
#[derive(Clone, Copy)]
struct Fe([u64; 5]);

impl Fe {
    const ZERO: Fe = Fe([0, 0, 0, 0, 0]);
    const ONE: Fe = Fe([1, 0, 0, 0, 0]);

    fn add(&self, other: &Fe) -> Fe {
        let [a0, a1, a2, a3, a4] = self.0;
        let [b0, b1, b2, b3, b4] = other.0;
        carry_u64([a0 + b0, a1 + b1, a2 + b2, a3 + b3, a4 + b4])
    }

    fn sub(&self, other: &Fe) -> Fe {
        let [a0, a1, a2, a3, a4] = self.0;
        let [b0, b1, b2, b3, b4] = other.0;
        let [p0, p1, p2, p3, p4] = TWO_P;
        // Adding 2p first keeps every limb non-negative: a limb of `other` is
        // at most 2^51 (see the invariant above) and every limb of 2p exceeds
        // that, so no subtraction borrows.
        carry_u64([
            a0 + p0 - b0,
            a1 + p1 - b1,
            a2 + p2 - b2,
            a3 + p3 - b3,
            a4 + p4 - b4,
        ])
    }

    fn neg(&self) -> Fe {
        Fe::ZERO.sub(self)
    }

    fn mul(&self, other: &Fe) -> Fe {
        let [a0, a1, a2, a3, a4] = self.0.map(u128::from);
        let [b0, b1, b2, b3, b4] = other.0.map(u128::from);
        // A product that lands above limb 4 wraps to limb 0 scaled by 19,
        // since 2^255 = 19 (mod p).
        let (b1_19, b2_19, b3_19, b4_19) = (b1 * 19, b2 * 19, b3 * 19, b4 * 19);
        carry_u128([
            a0 * b0 + a1 * b4_19 + a2 * b3_19 + a3 * b2_19 + a4 * b1_19,
            a0 * b1 + a1 * b0 + a2 * b4_19 + a3 * b3_19 + a4 * b2_19,
            a0 * b2 + a1 * b1 + a2 * b0 + a3 * b4_19 + a4 * b3_19,
            a0 * b3 + a1 * b2 + a2 * b1 + a3 * b0 + a4 * b4_19,
            a0 * b4 + a1 * b3 + a2 * b2 + a3 * b1 + a4 * b0,
        ])
    }

    fn sq(&self) -> Fe {
        self.mul(self)
    }

    /// Square-and-multiply over a 255-bit exponent, most significant bit
    /// first. The hand-optimised addition chains the reference implementations
    /// use are three times faster and immeasurably harder to check; a boot
    /// shim verifies one signature, so this takes the readable one.
    fn pow(&self, exponent: &[u8; 32]) -> Fe {
        let mut result = Fe::ONE;
        for i in (0..256).rev() {
            result = result.sq();
            if bit(exponent, i) == 1 {
                result = result.mul(self);
            }
        }
        result
    }

    fn invert(&self) -> Fe {
        self.pow(&P_MINUS_2)
    }

    /// The canonical 32-byte little-endian encoding: fully reduced mod p.
    fn to_bytes(self) -> [u8; 32] {
        let [mut t0, mut t1, mut t2, mut t3, mut t4] = carry_u64(self.0).0;
        // Weak reduction leaves a value in [0, 2p); decide whether p must come
        // off by adding 19 and watching for the carry out of the top limb.
        let mut q = (t0 + 19) >> 51;
        q = (t1 + q) >> 51;
        q = (t2 + q) >> 51;
        q = (t3 + q) >> 51;
        q = (t4 + q) >> 51;
        t0 += 19 * q;
        t1 += t0 >> 51;
        t0 &= MASK;
        t2 += t1 >> 51;
        t1 &= MASK;
        t3 += t2 >> 51;
        t2 &= MASK;
        t4 += t3 >> 51;
        t3 &= MASK;
        t4 &= MASK;

        let words = [
            t0 | (t1 << 51),
            (t1 >> 13) | (t2 << 38),
            (t2 >> 26) | (t3 << 25),
            (t3 >> 39) | (t4 << 12),
        ];
        let mut out = [0u8; 32];
        let (chunks, _) = out.as_chunks_mut::<8>();
        for (dst, word) in chunks.iter_mut().zip(words.iter()) {
            *dst = word.to_le_bytes();
        }
        out
    }

    /// Little-endian decode. Bit 255 is IGNORED (it is the sign bit in a point
    /// encoding, never part of the field element), and a value at or above p
    /// is accepted here and caught by the canonicity check in `decompress`.
    fn from_bytes(bytes: &[u8; 32]) -> Fe {
        let (chunks, _) = bytes.as_chunks::<8>();
        let word = |i: usize| {
            chunks
                .get(i)
                .copied()
                .map_or(0, |w: [u8; 8]| u64::from_le_bytes(w))
        };
        let (w0, w1, w2, w3) = (word(0), word(1), word(2), word(3));
        Fe([
            w0 & MASK,
            ((w0 >> 51) | (w1 << 13)) & MASK,
            ((w1 >> 38) | (w2 << 26)) & MASK,
            ((w2 >> 25) | (w3 << 39)) & MASK,
            (w3 >> 12) & MASK,
        ])
    }

    fn is_zero(self) -> bool {
        self.to_bytes() == [0u8; 32]
    }

    /// RFC 8032's sign convention: the least significant bit of the canonical
    /// encoding.
    fn is_odd(self) -> bool {
        self.to_bytes().first().is_some_and(|b| b & 1 == 1)
    }
}

impl PartialEq for Fe {
    fn eq(&self, other: &Fe) -> bool {
        self.to_bytes() == other.to_bytes()
    }
}

/// Propagate carries so every limb is at most 2^51. The top limb's overflow
/// wraps into limb 0 scaled by 19 (2^255 = 19 mod p), which can itself carry,
/// hence the final pass.
fn carry_u64(limbs: [u64; 5]) -> Fe {
    let [mut t0, mut t1, mut t2, mut t3, mut t4] = limbs;
    t1 += t0 >> 51;
    t0 &= MASK;
    t2 += t1 >> 51;
    t1 &= MASK;
    t3 += t2 >> 51;
    t2 &= MASK;
    t4 += t3 >> 51;
    t3 &= MASK;
    t0 += 19 * (t4 >> 51);
    t4 &= MASK;
    t1 += t0 >> 51;
    t0 &= MASK;
    Fe([t0, t1, t2, t3, t4])
}

fn carry_u128(limbs: [u128; 5]) -> Fe {
    let [mut t0, mut t1, mut t2, mut t3, mut t4] = limbs;
    t1 += t0 >> 51;
    t0 &= MASK128;
    t2 += t1 >> 51;
    t1 &= MASK128;
    t3 += t2 >> 51;
    t2 &= MASK128;
    t4 += t3 >> 51;
    t3 &= MASK128;
    t0 += 19 * (t4 >> 51);
    t4 &= MASK128;
    t1 += t0 >> 51;
    t0 &= MASK128;
    Fe([t0 as u64, t1 as u64, t2 as u64, t3 as u64, t4 as u64])
}

/// Bit `i` of a little-endian byte string, or 0 past its end.
fn bit(bytes: &[u8], i: usize) -> u8 {
    bytes.get(i >> 3).map_or(0, |b| (b >> (i & 7)) & 1)
}

// ---- the group ----

/// A curve point in extended coordinates (X:Y:Z:T), where x = X/Z, y = Y/Z and
/// T = XY/Z.
#[derive(Clone, Copy)]
struct Point {
    x: Fe,
    y: Fe,
    z: Fe,
    t: Fe,
}

impl Point {
    const IDENTITY: Point = Point {
        x: Fe::ZERO,
        y: Fe::ONE,
        z: Fe::ONE,
        t: Fe::ZERO,
    };

    /// add-2008-hwcd-3. Complete for a = -1 with d a non-square, so it needs
    /// no special case — including P + P and P + (-P).
    fn add(&self, other: &Point) -> Point {
        let a = self.y.sub(&self.x).mul(&other.y.sub(&other.x));
        let b = self.y.add(&self.x).mul(&other.y.add(&other.x));
        let c = self.t.mul(&D2).mul(&other.t);
        let d = self.z.mul(&other.z);
        let d = d.add(&d);
        let e = b.sub(&a);
        let f = d.sub(&c);
        let g = d.add(&c);
        let h = b.add(&a);
        Point {
            x: e.mul(&f),
            y: g.mul(&h),
            z: f.mul(&g),
            t: e.mul(&h),
        }
    }

    /// dbl-2008-hwcd. Algebraically `add(self, self)`, which the tests check,
    /// but it skips the T multiplications the general law needs.
    fn double(&self) -> Point {
        let a = self.x.sq();
        let b = self.y.sq();
        let c = self.z.sq();
        let c = c.add(&c);
        let d = a.neg();
        let e = self.x.add(&self.y).sq().sub(&a).sub(&b);
        let g = d.add(&b);
        let f = g.sub(&c);
        let h = d.sub(&b);
        Point {
            x: e.mul(&f),
            y: g.mul(&h),
            z: f.mul(&g),
            t: e.mul(&h),
        }
    }

    fn neg(&self) -> Point {
        Point {
            x: self.x.neg(),
            y: self.y,
            z: self.z,
            t: self.t.neg(),
        }
    }

    /// [scalar]self, double-and-add, most significant bit first.
    ///
    /// Deliberately NOT constant time: it branches on the scalar's bits. Both
    /// scalars a verification multiplies by are public — one is the signature's
    /// own S, the other the hash of data that travels with it — so there is no
    /// secret for the timing to leak.
    fn scalar_mul(&self, scalar: &[u8; 32]) -> Point {
        let mut acc = Point::IDENTITY;
        for i in (0..256).rev() {
            acc = acc.double();
            if bit(scalar, i) == 1 {
                acc = acc.add(self);
            }
        }
        acc
    }

    /// The 32-byte encoding: y with x's sign in the top bit.
    fn compress(&self) -> [u8; 32] {
        let zinv = self.z.invert();
        let x = self.x.mul(&zinv);
        let y = self.y.mul(&zinv);
        let mut out = y.to_bytes();
        if let Some(top) = out.last_mut() {
            *top |= u8::from(x.is_odd()) << 7;
        }
        out
    }

    /// Recover a point from its encoding, or `None` if the bytes are not one.
    ///
    /// Rejects a non-canonical y (an encoding of y + p, which names the same
    /// point through different bytes), a y for which no x exists, and the one
    /// x = 0 case where the sign bit would carry information the point does
    /// not have.
    fn decompress(bytes: &[u8; 32]) -> Option<Point> {
        let sign = bytes.last().map_or(0, |b| b >> 7);
        let mut without_sign = *bytes;
        if let Some(top) = without_sign.last_mut() {
            *top &= 0x7f;
        }
        let y = Fe::from_bytes(&without_sign);
        if y.to_bytes() != without_sign {
            return None; // y >= p: a second encoding of the same point
        }
        // x^2 = (y^2 - 1) / (d y^2 + 1) = u/v.
        let yy = y.sq();
        let u = yy.sub(&Fe::ONE);
        let v = yy.mul(&D).add(&Fe::ONE);
        // The candidate root, as (u/v)^((p+3)/8) without an inversion:
        // u v^3 (u v^7)^((p-5)/8).
        let v3 = v.sq().mul(&v);
        let v7 = v3.sq().mul(&v);
        let mut x = u.mul(&v3).mul(&u.mul(&v7).pow(&P_MINUS_5_DIV_8));
        let check = v.mul(&x.sq());
        if check != u {
            if check == u.neg() {
                x = x.mul(&SQRT_M1);
            } else {
                return None; // u/v is not a square: no such point
            }
        }
        if x.is_zero() && sign == 1 {
            return None; // -0 is not an encoding
        }
        if x.is_odd() != (sign == 1) {
            x = x.neg();
        }
        Some(Point {
            x,
            y,
            z: Fe::ONE,
            t: x.mul(&y),
        })
    }

    /// Whether this point has order 1, 2, 4 or 8 — the torsion subgroup that
    /// is not the prime-order group signatures live in. Such a public key
    /// verifies signatures nobody needed a private key to make.
    fn is_small_order(&self) -> bool {
        let eightfold = self.double().double().double();
        eightfold.is_identity()
    }

    /// Whether this point lies in the prime-order subgroup, i.e. carries NO
    /// torsion component: `[L]P` is the identity exactly then.
    ///
    /// This is the whole class that `is_small_order` only sampled. A key
    /// `A = B + T` for a torsion point `T` is not small order and passes that
    /// check, yet it is the key every torsion-shaped forgery is built on, and
    /// it is also where cofactored verifiers (libsodium, ZIP-215) and
    /// cofactorless ones like this disagree about the same bytes. An HONEST
    /// key cannot fail this: a public key is `[a]B`, which is in the
    /// prime-order subgroup by construction.
    fn is_torsion_free(&self) -> bool {
        self.scalar_mul(&store_words(L)).is_identity()
    }

    fn is_identity(&self) -> bool {
        // Projectively: X = 0 and Y = Z, which needs no inversion.
        self.x.is_zero() && self.y == self.z
    }
}

// ---- scalars mod L ----

fn load_words(bytes: &[u8; 32]) -> [u64; 4] {
    let (chunks, _) = bytes.as_chunks::<8>();
    let word = |i: usize| {
        chunks
            .get(i)
            .copied()
            .map_or(0, |w: [u8; 8]| u64::from_le_bytes(w))
    };
    [word(0), word(1), word(2), word(3)]
}

fn store_words(words: [u64; 4]) -> [u8; 32] {
    let mut out = [0u8; 32];
    let (chunks, _) = out.as_chunks_mut::<8>();
    for (dst, word) in chunks.iter_mut().zip(words.iter()) {
        *dst = word.to_le_bytes();
    }
    out
}

/// Whether `value >= L`, comparing from the most significant word down.
fn at_least_l(value: [u64; 4]) -> bool {
    for (v, l) in value.iter().rev().zip(L.iter().rev()) {
        if v != l {
            return v > l;
        }
    }
    true // equal to L
}

fn sub_l(value: [u64; 4]) -> [u64; 4] {
    let mut out = [0u64; 4];
    let mut borrow = 0u64;
    for ((slot, v), l) in out.iter_mut().zip(value.iter()).zip(L.iter()) {
        let (d, b1) = v.overflowing_sub(*l);
        let (d, b2) = d.overflowing_sub(borrow);
        *slot = d;
        borrow = u64::from(b1 || b2);
    }
    out
}

/// A signature's S must be the canonical representative mod L. Without this,
/// `S + L` — trivially computable by anyone holding the signature — is a
/// second signature that verifies for the same message.
fn is_canonical_scalar(bytes: &[u8; 32]) -> bool {
    !at_least_l(load_words(bytes))
}

/// A 64-byte little-endian hash reduced mod L.
///
/// Bit by bit, most significant first: `r = 2r + bit`, then one conditional
/// subtraction, which suffices because doubling a value below L leaves it
/// below 2L. The reference implementations use a Barrett-style reduction over
/// packed 21-bit limbs that is far faster and essentially unreviewable; this
/// runs 512 times per verification and takes microseconds.
fn reduce_wide(hash: &[u8; 64]) -> [u8; 32] {
    let mut r = [0u64; 4];
    for byte in hash.iter().rev() {
        for shift in (0..8).rev() {
            // r = 2r + bit: r < L < 2^253, so this cannot overflow 4 words.
            let mut carry = u64::from((byte >> shift) & 1);
            for slot in r.iter_mut() {
                let next = *slot >> 63;
                *slot = (*slot << 1) | carry;
                carry = next;
            }
            if at_least_l(r) {
                r = sub_l(r);
            }
        }
    }
    store_words(r)
}

// ---- verification ----

/// Whether `signature` is a valid ed25519 signature of `message` under
/// `public_key`.
///
/// Every failure is this one `false`: a malformed key, a malformed signature,
/// a non-canonical S, a small-order key and a signature that simply does not
/// verify are not distinguished. That is deliberate — the caller has exactly
/// one question and no way to spell an answer that is not "reject".
#[must_use]
pub fn verify(
    public_key: &[u8; PUBLIC_KEY_LEN],
    message: &[u8],
    signature: &[u8; SIGNATURE_LEN],
) -> bool {
    let (chunks, _) = signature.as_chunks::<32>();
    let (Some(r_bytes), Some(s_bytes)) = (chunks.first(), chunks.get(1)) else {
        return false;
    };
    if !is_canonical_scalar(s_bytes) {
        return false;
    }
    let Some(a) = Point::decompress(public_key) else {
        return false;
    };
    // The key must be in the prime-order subgroup and must not be the
    // identity — between them, every point with a torsion component and every
    // small-order point. `is_torsion_free` alone would admit the identity
    // (`[L]O` is `O`), and the identity signs for everybody.
    if a.is_identity() || !a.is_torsion_free() {
        return false;
    }
    // R is decompressed ONLY to refuse a small-order one. With A already
    // torsion-free this is defence in depth rather than the load-bearing
    // check — see `a_mixed_order_key_is_refused`, which is refused by the key
    // policy above — but R is attacker-supplied where A is pinned, and three
    // doublings are not worth reasoning about. The equation below still
    // compares ENCODINGS, so a non-canonical R stays a rejection either way:
    // it fails to decompress here, and could never equal a canonical
    // re-encoding there.
    let Some(r_point) = Point::decompress(r_bytes) else {
        return false;
    };
    if r_point.is_small_order() {
        return false;
    }
    let Some(base) = Point::decompress(&BASE_POINT) else {
        return false;
    };

    let mut hasher = sha512::Sha512::new();
    hasher.update(r_bytes);
    hasher.update(public_key);
    hasher.update(message);
    let k = reduce_wide(&hasher.finalize());

    // R = [S]B - [k]A. Comparing ENCODINGS rather than decompressing R is what
    // makes a non-canonical R a rejection for free.
    let expected = base.scalar_mul(s_bytes).add(&a.scalar_mul(&k).neg());
    expected.compress() == *r_bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Decode a hex literal, REFUSING anything that is not exactly `N` bytes
    /// of lowercase hex. The forgiving version this replaces mapped a stray
    /// character to nibble 0 and right-padded a short string, so a mistyped
    /// literal in a negative test still decoded to *some* value and the
    /// assertion could hold for a reason that had nothing to do with the
    /// property being tested.
    fn hex_nibble(c: u8) -> Option<u8> {
        match c {
            b'0'..=b'9' => Some(c - b'0'),
            b'a'..=b'f' => Some(c - b'a' + 10),
            _ => None,
        }
    }

    fn from_hex<const N: usize>(s: &str) -> [u8; N] {
        assert_eq!(s.len(), N * 2, "hex literal must be {N} bytes: {s}");
        let (pairs, _) = s.as_bytes().as_chunks::<2>();
        let decoded: Option<Vec<u8>> = pairs
            .iter()
            .map(|pair| {
                let [hi, lo] = *pair;
                Some((hex_nibble(hi)? << 4) | hex_nibble(lo)?)
            })
            .collect();
        let decoded = decoded.unwrap_or_default();
        assert_eq!(decoded.len(), N, "not lowercase hex: {s}");
        let mut out = [0u8; N];
        out.copy_from_slice(&decoded);
        out
    }

    // ---- the constants ----

    #[test]
    fn the_curve_constants_are_what_their_names_say() {
        let small = |v: u64| Fe([v, 0, 0, 0, 0]);
        // d = -121665/121666, recomputed from the two integers that define it.
        assert!(D == small(121665).neg().mul(&small(121666).invert()));
        assert!(D2 == D.add(&D));
        // Either square root of -1 would serve — the sign is settled
        // afterwards by the encoding's sign bit — so squaring it is the whole
        // property. (That d is a NON-square, which is what makes the addition
        // law complete, is not asserted directly; the group-law tests below
        // are what would fail if it were not.)
        assert!(SQRT_M1.sq() == Fe::ONE.neg());
        // 2p is a multiple of p, so it reduces to zero.
        assert!(carry_u64(TWO_P).is_zero());
    }

    // ---- the field ----

    #[test]
    fn field_round_trips_through_its_encoding() {
        for seed in 0u8..32 {
            let mut bytes = [seed; 32];
            if let Some(top) = bytes.last_mut() {
                *top &= 0x7f;
            }
            assert_eq!(Fe::from_bytes(&bytes).to_bytes(), bytes, "seed {seed}");
        }
    }

    #[test]
    fn p_and_zero_are_the_same_element() {
        // p itself decodes to a weakly-reduced zero, and to_bytes must
        // canonicalise it. This is the case the decompression canonicity check
        // exists to reject at the encoding level.
        let p: [u8; 32] =
            from_hex("edffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f");
        assert!(Fe::from_bytes(&p).is_zero());
        assert_ne!(Fe::from_bytes(&p).to_bytes(), p);
    }

    #[test]
    fn inversion_undoes_multiplication() {
        for seed in 1u8..8 {
            let mut bytes = [seed.wrapping_mul(37); 32];
            if let Some(top) = bytes.last_mut() {
                *top &= 0x7f;
            }
            let a = Fe::from_bytes(&bytes);
            assert!(a.mul(&a.invert()) == Fe::ONE, "seed {seed}");
        }
    }

    #[test]
    fn subtraction_is_the_inverse_of_addition() {
        let a = Fe::from_bytes(&[0x11; 32]);
        let b = Fe::from_bytes(&[0x9e; 32]);
        assert!(a.add(&b).sub(&b) == a);
        assert!(a.sub(&b).add(&b) == a);
        assert!(a.add(&a.neg()).is_zero());
    }

    // ---- the group law ----

    /// The base point.
    ///
    /// The ASSERT is the point of it. This used to fall back to the identity,
    /// which is the one value that satisfies every algebraic law the tests
    /// below assert: a decompress that returned `None` would have left
    /// doubling-equals-addition, associativity, order-L, repeated-addition and
    /// round-tripping all comparing the identity to itself and passing
    /// vacuously — five of the six tests the commit message names as what pins
    /// this file's correctness. Failing here instead reds every one of them.
    fn base() -> Point {
        let decoded = Point::decompress(&BASE_POINT);
        assert!(decoded.is_some(), "the base point must decompress");
        decoded.unwrap_or(Point::IDENTITY)
    }

    #[test]
    fn the_base_point_decompresses_to_its_known_coordinates() {
        let decoded = Point::decompress(&BASE_POINT).map(|b| (b.x.to_bytes(), b.y.to_bytes()));
        // y = 4/5 mod p — whose encoding IS `BASE_POINT`, the x being even so
        // the sign bit is clear — and that even x, both little-endian.
        let expected_x: [u8; 32] =
            from_hex("1ad5258f602d56c9b2a7259560c72c695cdcd6fd31e2a4c0fe536ecdd3366921");
        assert_eq!(decoded, Some((expected_x, BASE_POINT)));
    }

    #[test]
    fn doubling_agrees_with_adding_a_point_to_itself() {
        // The two formulas are independent code paths for one operation, so
        // this checks both against each other rather than a table.
        let mut p = base();
        for step in 0..8 {
            assert_eq!(p.double().compress(), p.add(&p).compress(), "step {step}");
            p = p.add(&base());
        }
    }

    #[test]
    fn the_group_law_is_associative_and_has_an_identity() {
        let a = base();
        let b = base().double();
        let c = base().double().double();
        assert_eq!(a.add(&b).add(&c).compress(), a.add(&b.add(&c)).compress());
        assert_eq!(a.add(&Point::IDENTITY).compress(), a.compress());
        assert_eq!(a.add(&a.neg()).compress(), Point::IDENTITY.compress());
    }

    #[test]
    fn the_base_point_has_order_l() {
        // [L]B is the identity: the single strongest statement about the base
        // point, D2 and the addition law all being right at once.
        assert!(base().scalar_mul(&store_words(L)).is_identity());
    }

    #[test]
    fn scalar_multiplication_is_repeated_addition() {
        let mut sum = Point::IDENTITY;
        for n in 0u8..16 {
            let mut scalar = [0u8; 32];
            if let Some(slot) = scalar.first_mut() {
                *slot = n;
            }
            assert_eq!(
                base().scalar_mul(&scalar).compress(),
                sum.compress(),
                "n = {n}"
            );
            sum = sum.add(&base());
        }
    }

    #[test]
    fn compression_round_trips() {
        let mut p = base();
        for step in 0..16 {
            let bytes = p.compress();
            let again = Point::decompress(&bytes).map(|q| q.compress());
            assert_eq!(again, Some(bytes), "step {step}");
            p = p.add(&base());
        }
    }

    #[test]
    fn the_identity_and_small_order_points_are_recognised() {
        assert!(Point::IDENTITY.is_small_order());
        // y = -1 is the order-2 point.
        let order_two: [u8; 32] =
            from_hex("ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f");
        assert_eq!(
            Point::decompress(&order_two).map(|p| p.is_small_order()),
            Some(true)
        );
        assert!(!base().is_small_order());
    }

    #[test]
    fn a_non_canonical_encoding_does_not_decompress() {
        // y = p is zero by value but not a canonical encoding of it.
        let p_encoded: [u8; 32] =
            from_hex("edffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f");
        assert!(Point::decompress(&p_encoded).is_none());
    }

    // ---- scalars ----

    #[test]
    fn l_itself_is_not_a_canonical_scalar() {
        assert!(!is_canonical_scalar(&store_words(L)));
        let mut below = store_words(L);
        if let Some(slot) = below.first_mut() {
            *slot -= 1;
        }
        assert!(is_canonical_scalar(&below));
    }

    // ---- signatures ----

    /// Signatures `ring` produced from fixed seeds — the anchor that keeps
    /// THIS crate testable alone, with no dependency and no network. The live
    /// cross-check against `ring` on fresh keys lives in
    /// `net/src/ed25519_cross.rs`; these four are what it committed, so a
    /// change here that still satisfies the algebra above but disagrees with
    /// the rest of the world reds without `ring` present.
    ///
    /// Each was signed with a seed of one repeated byte over the message
    /// `(0..len).map(|i| i % 251)`; the seed is recorded so any ed25519
    /// implementation can regenerate the pair.
    const RING_VECTORS: [(u8, usize, &str, &str); 4] = [
        (
            0x01,
            0,
            "8a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c",
            "778cda0634c021fae8b1a9fa655ba13230f6fcfc5c5d519afb0872ec9bf1d642\
             41cc3eed8ad47270d86d30e762ad17677c6fb1797e35bca7eba30388257e020f",
        ),
        (
            0x02,
            3,
            "8139770ea87d175f56a35466c34c7ecccb8d8a91b4ee37a25df60f5b8fc9b394",
            "5bd19de4e8f23d28876e658ddab3de0ffb6aab22440914c56d780376760c0995\
             28a060cc913a5ce30e43a09225b0d40dc8900ba6c49df8e165424bdf0a3d3e0c",
        ),
        (
            0x03,
            64,
            "ed4928c628d1c2c6eae90338905995612959273a5c63f93636c14614ac8737d1",
            "76907dd0db68cfa83a5f22e1583314b82c5d74de919eaad4f78d96be172c76dc\
             a05828a1a17a8a0e1394bdb2f29583886d14e01dadac4ae7735dcc50afd14503",
        ),
        (
            0x04,
            200,
            "ca93ac1705187071d67b83c7ff0efe8108e8ec4530575d7726879333dbdabe7c",
            "094adad5a4ef87699a1b5f362114623b8f05a839d99b627655fede71d5e0a868\
             8d3e6021301645ef33b30a3339a3861e2a9c0b5ad1616cecfbeb4a11f6e59409",
        ),
    ];

    fn vector_message(len: usize) -> Vec<u8> {
        (0..len).map(|i| (i % 251) as u8).collect()
    }

    #[test]
    fn known_good_signatures_verify() {
        for (seed, len, public_hex, signature_hex) in RING_VECTORS {
            let public: [u8; 32] = from_hex(public_hex);
            let signature: [u8; 64] = from_hex(signature_hex);
            assert!(
                verify(&public, &vector_message(len), &signature),
                "seed {seed:#04x} over {len} bytes"
            );
        }
    }

    #[test]
    fn a_known_good_signature_stops_verifying_when_anything_moves() {
        // The same four vectors as the negative case: a verifier that accepts
        // everything passes the test above and fails this one.
        for (seed, len, public_hex, signature_hex) in RING_VECTORS {
            let public: [u8; 32] = from_hex(public_hex);
            let signature: [u8; 64] = from_hex(signature_hex);

            let mut wrong_key = public;
            if let Some(slot) = wrong_key.first_mut() {
                *slot ^= 1;
            }
            assert!(
                !verify(&wrong_key, &vector_message(len), &signature),
                "seed {seed:#04x}: a changed key still verified"
            );

            for index in [0usize, 31, 32, 63] {
                let mut broken = signature;
                if let Some(slot) = broken.get_mut(index) {
                    *slot ^= 1;
                }
                assert!(
                    !verify(&public, &vector_message(len), &broken),
                    "seed {seed:#04x}: signature byte {index} changed and still verified"
                );
            }

            let mut longer = vector_message(len);
            longer.push(0);
            assert!(
                !verify(&public, &longer, &signature),
                "seed {seed:#04x}: an extended message still verified"
            );
        }
    }

    #[test]
    fn a_small_order_key_cannot_sign_for_everything() {
        // The danger a small-order key IS, built rather than described. Take A
        // = the identity: [k]A is the identity whatever k is, so the
        // verification equation collapses to R = [S]B, which does not mention
        // the message at all. Any S below L therefore yields a signature that
        // verifies for EVERY message under that key — no private key needed.
        //
        // An all-zero signature would be rejected by the equation itself and
        // so proves nothing about the refusal; this one is refused only
        // because the key is.
        let key = Point::IDENTITY.compress();
        let mut s = [0u8; 32];
        if let Some(slot) = s.first_mut() {
            *slot = 7;
        }
        let r = base().scalar_mul(&s).compress();
        let mut signature = [0u8; 64];
        if let Some(dst) = signature.get_mut(..32) {
            dst.copy_from_slice(&r);
        }
        if let Some(dst) = signature.get_mut(32..) {
            dst.copy_from_slice(&s);
        }
        for message in [b"one message".as_slice(), b"a completely different one"] {
            assert!(
                !verify(&key, message, &signature),
                "a small-order key signed for an arbitrary message"
            );
        }
    }

    /// The order-2 point, y = -1.
    fn torsion_point() -> Option<Point> {
        let order_two: [u8; 32] =
            from_hex("ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f");
        Point::decompress(&order_two)
    }

    #[test]
    fn the_prime_order_subgroup_check_separates_honest_keys_from_torsion() {
        // What `is_small_order` alone could not say. Each of these is a point
        // the check must classify differently, and the Option comparison makes
        // a decompression failure a red rather than a skip.
        assert!(base().is_torsion_free(), "an honest key is [a]B");
        assert_eq!(
            torsion_point().map(|t| t.is_torsion_free()),
            Some(false),
            "a pure torsion point is not in the prime-order subgroup"
        );
        assert_eq!(
            torsion_point().map(|t| base().add(&t).is_torsion_free()),
            Some(false),
            "B + T carries a torsion component"
        );
        assert_eq!(
            torsion_point().map(|t| base().add(&t).is_small_order()),
            Some(false),
            "B + T is MIXED order — which is exactly why is_small_order misses it"
        );
        // The identity satisfies [L]O = O, so this check alone would admit it;
        // `verify` refuses it separately.
        assert!(Point::IDENTITY.is_torsion_free());
        assert!(Point::IDENTITY.is_identity());
    }

    /// `challenge` for a candidate signature: k = H(R, A, M) reduced mod L.
    fn challenge(r_bytes: &[u8; 32], key: &[u8; 32], message: &[u8]) -> [u8; 32] {
        let mut hasher = crate::sha512::Sha512::new();
        hasher.update(r_bytes);
        hasher.update(key);
        hasher.update(message);
        reduce_wide(&hasher.finalize())
    }

    fn signature_of(r_bytes: &[u8; 32], s: &[u8; 32]) -> [u8; 64] {
        let mut signature = [0u8; 64];
        if let Some(dst) = signature.get_mut(..32) {
            dst.copy_from_slice(r_bytes);
        }
        if let Some(dst) = signature.get_mut(32..) {
            dst.copy_from_slice(s);
        }
        signature
    }

    /// `scalar + small` mod L. `scalar` is below L and `small` is tiny, so the
    /// sum is below 2L and one conditional subtraction reduces it.
    fn scalar_plus(scalar: &[u8; 32], small: u64) -> [u8; 32] {
        let mut words = load_words(scalar);
        let mut carry = u128::from(small);
        for slot in words.iter_mut() {
            let sum = u128::from(*slot) + carry;
            *slot = sum as u64;
            carry = sum >> 64;
        }
        if at_least_l(words) {
            words = sub_l(words);
        }
        store_words(words)
    }

    #[test]
    fn a_mixed_order_key_is_refused() {
        // The signature a small-order KEY refusal does not catch, built rather
        // than described. Take A = B + T with T of order 2 and the "private
        // key" a = 1: A is not small order, so that check passes it. Sign
        // ordinarily with a nonce r = 5, giving S = 5 + k:
        //
        //     [S]B - [k]A = [5+k]B - [k]B - [k]T = [5]B - [k]T
        //
        // which is [5]B — and so equals R — whenever k is EVEN, since T doubles
        // to nothing. R = [5]B is NOT small order, so the small-order-R check
        // below cannot be what refuses this: only the prime-order-subgroup
        // requirement on A can, which is what this test pins.
        let Some(t) = torsion_point() else {
            return;
        };
        let a = base().add(&t);
        assert!(!a.is_small_order(), "A must survive the small-order check");
        let key = a.compress();
        let nonce = scalar_plus(&[0u8; 32], 5);
        let r_point = base().scalar_mul(&nonce);
        assert!(!r_point.is_small_order(), "R must not be small order");
        let r_bytes = r_point.compress();

        let mut built = false;
        for probe in 0u8..64 {
            let message = [probe];
            let k = challenge(&r_bytes, &key, &message);
            if bit(&k, 0) == 1 {
                continue; // odd k leaves [k]T = T, so the equation misses R
            }
            let signature = signature_of(&r_bytes, &scalar_plus(&k, 5));
            // The equation really is satisfied — this is refused for the key it
            // is under, not because it fails to verify.
            let expected = base()
                .scalar_mul(&scalar_plus(&k, 5))
                .add(&a.scalar_mul(&k).neg());
            assert_eq!(
                expected.compress(),
                r_bytes,
                "probe {probe}: the constructed signature does not satisfy the equation"
            );
            assert!(
                !verify(&key, &message, &signature),
                "probe {probe}: a signature under a mixed-order key was accepted"
            );
            built = true;
            break;
        }
        assert!(built, "no message in 64 probes produced an even k");
    }

    #[test]
    fn a_small_order_r_is_refused() {
        // The other half, isolated so it pins the R check and nothing else.
        // The key here is the base point itself — torsion-free, the shape an
        // honest key has — so the subgroup requirement above passes it. With
        // a = 1, choosing R = the identity and S = k gives
        //
        //     [S]B - [k]A = [k]B - [k]B = O = R
        //
        // for EVERY message, with no parity condition. It is a real signature
        // by whoever holds a, and a degenerate one: r = 0, so R carries no
        // nonce at all. Only the small-order-R refusal rejects it.
        let key = base().compress();
        let r_bytes = Point::IDENTITY.compress();
        for message in [b"one message".as_slice(), b"a completely different one"] {
            let k = challenge(&r_bytes, &key, message);
            let signature = signature_of(&r_bytes, &k);
            let expected = base().scalar_mul(&k).add(&base().scalar_mul(&k).neg());
            assert_eq!(
                expected.compress(),
                r_bytes,
                "the constructed signature does not satisfy the equation"
            );
            assert!(
                !verify(&key, message, &signature),
                "a signature with R at the identity was accepted"
            );
        }
    }

    #[test]
    fn s_at_or_above_l_is_refused() {
        // Malleability: (S + L) mod L is S, so a verifier that reduces rather
        // than REFUSING would accept a second signature for the same message
        // that nobody with the private key ever produced.
        let Some((_, len, public_hex, signature_hex)) = RING_VECTORS.first().copied() else {
            return;
        };
        let public: [u8; 32] = from_hex(public_hex);
        let signature: [u8; 64] = from_hex(signature_hex);
        assert!(verify(&public, &vector_message(len), &signature));

        let s: [u8; 32] = signature
            .get(32..64)
            .and_then(|s| s.try_into().ok())
            .unwrap_or([0u8; 32]);
        let mut words = load_words(&s);
        let mut carry = 0u128;
        for (slot, l) in words.iter_mut().zip(L.iter()) {
            let sum = u128::from(*slot) + u128::from(*l) + carry;
            *slot = sum as u64;
            carry = sum >> 64;
        }
        let mut malleable = signature;
        if let Some(dst) = malleable.get_mut(32..64) {
            dst.copy_from_slice(&store_words(words));
        }
        assert_ne!(malleable, signature);
        assert!(!verify(&public, &vector_message(len), &malleable));
    }

    #[test]
    fn reduce_wide_agrees_with_small_values() {
        // A value below L must survive reduction unchanged.
        let mut wide = [0u8; 64];
        if let Some(dst) = wide.get_mut(..4) {
            dst.copy_from_slice(&[1, 2, 3, 4]);
        }
        let mut expected = [0u8; 32];
        if let Some(dst) = expected.get_mut(..4) {
            dst.copy_from_slice(&[1, 2, 3, 4]);
        }
        assert_eq!(reduce_wide(&wide), expected);
    }

    #[test]
    fn reduce_wide_maps_l_to_zero_and_l_plus_one_to_one() {
        let mut wide = [0u8; 64];
        if let Some(dst) = wide.get_mut(..32) {
            dst.copy_from_slice(&store_words(L));
        }
        assert_eq!(reduce_wide(&wide), [0u8; 32]);
        if let Some(slot) = wide.first_mut() {
            *slot += 1;
        }
        let mut one = [0u8; 32];
        if let Some(slot) = one.first_mut() {
            *slot = 1;
        }
        assert_eq!(reduce_wide(&wide), one);
    }
}
